apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    name: ${NAME}
  name: ${NAME}-cronjob
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "${NAME}-${TAG}"
    labels:
      name: "${NAME}"
      environment: "${TAG}"
      role: "${ROLE}"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
    failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
    jobTemplate:
      metadata:
        labels:
          name: "${NAME}"
          environment: "${TAG}"
          role: "${ROLE}"
      spec:
        backoffLimit: ${{JOB_BACKOFF_LIMIT}}
        template:
          metadata:
            labels:
              name: "${NAME}"
              environment: "${TAG}"
              role: "${ROLE}"
          spec:
            containers:
              - name: "${NAME}-${TAG}"
                image: "${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${NAME}:${TAG}"
                imagePullPolicy: Always
                command:
                  - /bin/sh
                  - -c
                  - cd /opt/app-root; ./run.sh
                env:
                  - name: PG_USER
                    valueFrom:
                      secretKeyRef:
                        key: database-user
                        name: postgresql-${TAG}-secret
                  - name: PG_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: database-password
                        name: postgresql-${TAG}-secret
                  - name: PG_DB_NAME
                    valueFrom:                         
                      secretKeyRef:
                        key: DATABASE_NAME
                        name: legal-api-${TAG}-secret
                  - name: PG_HOST
                    valueFrom:
                      secretKeyRef:
                        key: DATABASE_HOST
                        name: legal-api-${TAG}-secret
                  - name: PG_PORT
                    valueFrom:
                      secretKeyRef:
                        key: DB_PORT
                        name: legal-api-${TAG}-secret
                  - name: APP_FILE
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: APP_FILE
                  - name: SENDER_EMAIL
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SENDER_EMAIL
                  - name: ERROR_EMAIL_RECIPIENTS
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: ERROR_EMAIL_RECIPIENTS
                  - name: INCORPORATION_FILINGS_DAILY_REPORT_RECIPIENTS
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: INCORPORATION_FILINGS_DAILY_REPORT_RECIPIENTS
                  - name: COOP_FILINGS_MONTHLY_REPORT_RECIPIENTS
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: COOP_FILINGS_MONTHLY_REPORT_RECIPIENTS
                  - name: COOPERATIVE_MONTHLY_REPORT_RECIPIENTS
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: COOPERATIVE_MONTHLY_REPORT_RECIPIENTS
                  - name: BC_STATS_MONTHLY_REPORT_RECIPIENTS
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: BC_STATS_MONTHLY_REPORT_RECIPIENTS      
                  - name: MONTH_REPORT_DATES
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: MONTH_REPORT_DATES      
                  - name: EMAIL_SMTP
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: EMAIL_SMTP
                  - name: RETRY_TIMES
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: RETRY_TIMES
                  - name: RETRY_INTERVAL
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: RETRY_INTERVAL
                  - name: ENVIRONMENT
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: ENVIRONMENT                   
            restartPolicy: "Never"
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 1600
            dnsPolicy: "ClusterFirst"
parameters: 

  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: filings-notebook-report

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: job

  - name: NAMESPACE
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: cc892f

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: cc892f-tools

  - name: IMAGE_REGISTRY
    displayName: Image Registry
    required: true
    description: The image registry of the OpenShift project.
    value: image-registry.openshift-image-registry.svc:5000

  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job (using local cluster system TZ)"
    value: "30 14 * * *"
    required: true

  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true

  - name: "FAILED_JOBS_HISTORY_LIMIT"
    displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained"
    value: "2"
    required: true

  - name: "JOB_BACKOFF_LIMIT"
    displayName: "Job Backoff Limit"
    description: "The number of attempts to try for a successful job outcome"
    value: "0"
    required: false
