apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
        app: ${NAME}
        name: ${NAME}-${TAG}
    name: ${NAME}-${TAG}-pipeline
  spec:
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO_URL}
        type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${JENKINS_FILE}
      type: JenkinsPipeline
parameters:
- description: |
    The name assigned to all of the objects defined in this template.
    You should keep this as default unless your know what your doing.
  displayName: Name
  name: NAME
  required: true
  value: update-legal-filings
- name: TAG
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  value: dev
  required: true
- description: |
    The URL to your GIT repo, don't use the this default unless
    your just experimenting.
  displayName: Git Repo URL
  name: GIT_REPO_URL
  required: true
  value: https://github.com/bcgov/lear.git
- description: The git reference or branch.
  displayName: Git Reference
  name: GIT_REF
  required: true
  value: master
- description: The source context directory.
  displayName: Source Context Directory
  name: SOURCE_CONTEXT_DIR
  required: false
  value: jobs/update-legal-filings
- description: The Jenkinsfile this pipeline should use.
  displayName: The Jenksinfile this pipeline should use.
  name: JENKINS_FILE
  required: false
  value: ./Jenkinsfiles/dev.groovy

