---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "future-effective-filings"
  annotations:
    description: "Scheduled task to send future effective filings to the entity filer queue"
    tags: "cronjob"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "future-effective-filings"
  spec:
    concurrencyPolicy: "Forbid"
    schedule: "0 * * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "future-effective-filings"
              image: "docker-registry.default.svc:5000/gl2uos-tools/future-effective-filings:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                - name: COLIN_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ROUTE
                      name: colin-api-${ENV_TAG}-config
                - name: LEGAL_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ROUTE
                      name: legal-api-${ENV_TAG}-config
                - name: AUTH_URL
                  valueFrom:
                    configMapKeyRef:
                      key: AUTH_URL
                      name: updater-jobs-${ENV_TAG}-config
                - name: AUTH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_USERNAME
                      name: updater-job
                - name: AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_PASSWORD
                      name: updater-job
                - name: SENTRY_DSN
                  valueFrom:
                    configMapKeyRef:
                      key: SENTRY_DSN
                      name: updater-jobs-${ENV_TAG}-config
                - name: NATS_SERVERS
                  valueFrom:
                    configMapKeyRef:
                      key: NATS_SERVERS
                      name: entity-filer-${ENV_TAG}-config
                - name: NATS_CLIENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: NATS_CLIENT_NAME
                      name: entity-filer-${ENV_TAG}-config
                - name: NATS_CLUSTER_ID
                  valueFrom:
                    configMapKeyRef:
                      key: NATS_CLUSTER_ID
                      name: entity-filer-${ENV_TAG}-config
                - name: NATS_FILER_SUBJECT
                  valueFrom:
                    configMapKeyRef:
                      key: NATS_FILER_SUBJECT
                      name: entity-filer-${ENV_TAG}-config
                - name: NATS_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      key: NATS_QUEUE
                      name: entity-filer-${ENV_TAG}-config
            restartPolicy: "Never"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "dev"
        },
]
