apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: entity-pay
  namespace: gl2uos-tools
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: 'docker-registry.default.svc:5000/gl2uos-tools/entity-pay'
