codecov:
  require_ci_to_pass: true
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: auto
        flags:
          - colinapi
          - legalapi
          - entityemailer
          - entityfiler
          - entitypay
          - entitybn
          - entity-digital-credentials
          - furnishings
          - involuntary-dissolutions

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  colinapi:
    paths:
      - colin-api/src/colin_api
    carryforward: true
  legalapi:
    paths:
      - legal-api/src/legal_api
    carryforward: true
  entityemailer:
    paths:
      - queue_services/entity-emailer/src/entity_emailer
    carryforward: true
  entityfiler:
    paths:
      - queue_services/entity-filer/src/entity_filer
    carryforward: true
  entitypay:
    paths:
      - queue_services/entity-pay/src/entity_pay
    carryforward: true
  entitybn:
    paths:
      - queue_services/entity-bn/src/entity_bn
    carryforward: true
  entity-digital-credentials:
    paths:
      - queue_services/entity-digital-credentials/src/entity_digital_credentials
    carryforward: true
  furnishings:
    paths:
      - jobs/furnishings
    carryforward: true
  involuntary-dissolutions:
    paths:
      - jobs/involuntary-dissolutions
    carryforward: true
