codecov:
  require_ci_to_pass: true
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: auto
        flags:
          - business-api
          - business-bn
          - business-bn-retry
          - business-digital-credentials
          - business-email-reminder
          - business-emailer
          - business-entity-bn
          - business-expired-limited-restoration
          - business-filer
          - business-filings-notebook-report
          - business-furnishings
          - business-future-effective-filings
          - business-involuntary-dissolutions
          - business-pay
          - business-registry-model
          - business-update-colin-filings
          - business-update-legal-filings

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  business-api:
    paths:
      - legal-api/src/legal_api
    carryforward: true
  business-bn:
    paths:
      - queue_services/business-bn/src/business_bn
    carryforward: true
  business-bn-retry:
    paths:
      - gcp-jobs/bn-retry/src/bn_retry
    carryforward: true
  business-digital-credentials:
    paths:
      - queue_services/business-digital-credentials/src/business_digital_credentials
    carryforward: true
  business-email-reminder:
    paths:
      - gcp-jobs/email-reminder/src/email_reminder
    carryforward: true
  business-emailer:
    paths:
      - queue_services/business-emailer/src/business_emailer
    carryforward: true
  business-entity-bn:
    paths:
      - gcp-jobs/entity-bn/src/entity-bn
    carryforward: true
  business-expired-limited-restoration:
    paths:
      - gcp-jobs/expired-limited-restoration/src/expired_limited_restoration
    carryforward: true
  business-filer:
    paths:
      - queue_services/business-filer/src/business_filer
    carryforward: true
  business-filings-notebook-report:
    paths:
      - gcp-jobs/filings-notebook-report/src/notebookreport
    carryforward: true
  business-furnishings:
    paths:
      - gcp-jobs/furnishings/src/furnishings
    carryforward: true
  business-future-effective-filings:
    paths:
      - gcp-jobs/future-effective-filings/src/future_effective_filings
    carryforward: true
  business-involuntary-dissolutions:
    paths:
      - gcp-jobs/involuntary-dissolutions/src/involuntary_dissolutions
    carryforward: true
  business-pay:
    paths:
      - queue_services/business-pay/src/business_pay
    carryforward: true
  business-registry-model:
    paths:
      - python/common/business-registry-model/src/business_model
    carryforward: true
  business-update-colin-filings:
    paths:
      - gcp-jobs/update-colin-filings/src/update_colin_filings
    carryforward: true
  business-update-legal-filings:
    paths:
      - gcp-jobs/update-legal-filings/src/update_legal_filings
    carryforward: true
