apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
parameters:
parameters:
  - description: |
      The name assigned to all of the objects defined in this template.
      You should keep this as default unless your know what your doing.
    displayName: Name
    name: NAME
    required: true
    value: sftp-nuans-report
