"""empty message

Revision ID: 9e36cf10f47c
Revises: e62e82cc80e0
Create Date: 2023-06-13 10:40:39.521652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e36cf10f47c'
down_revision = 'e62e82cc80e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colin_event_ids', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['colin_event_id'])

    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_filing_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_legal_entities_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_foreign_key(None, 'filings', ['change_filing_id'], ['id'])

    with op.batch_alter_table('legal_entities_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_legal_entities_history_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_foreign_key(None, 'filings', ['change_filing_id'], ['id'])

    with op.batch_alter_table('users_history', schema=None) as batch_op:
        batch_op.alter_column('sub',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=1024),
               existing_nullable=True,
               autoincrement=False)
        batch_op.alter_column('idp_userid',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_history', schema=None) as batch_op:
        batch_op.alter_column('idp_userid',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True,
               autoincrement=False)
        batch_op.alter_column('sub',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('legal_entities_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_legal_entities_history_change_filing_id'))
        batch_op.drop_column('change_filing_id')

    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_legal_entities_change_filing_id'))
        batch_op.drop_column('change_filing_id')

    with op.batch_alter_table('colin_event_ids', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
