# table_name                       load_phase
mig_group                          20
mig_batch                          30
mig_corp_batch                     40
mig_corp_account                   40
corp_processing                    50
colin_tracking                     50
auth_processing                    50
auth_component_operation           60
email_domain_groups                10
bad_emails                         10
excluded_emails                    10
excluded_email_domains             10
excluded_email_domain_patterns     10
exclude_corps                      10
corps_with_third_party             10
bar_corps                          10
demigrated_filings                 10
