version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "legal_api_postgres"
    ports:
      - "${DATABASE_TEST_PORT}:5432"
    environment:
      LC_ALL: "C.UTF-8"
      POSTGRES_DB: "${DATABASE_TEST_NAME}"
      POSTGRES_USER: "${DATABASE_TEST_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_TEST_PASSWORD}"
