version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "legal_api_postgres"
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=legal_test
      - POSTGRES_USER=legal
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
