---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-${TAG}-deployment-template
  annotations:
    description:
      Deployment template for an API application and connect to database.
    tags: Flask
    iconClass: icon-python
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}
        environment: ${TAG}
        role: ${ROLE}
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: "[{name: ${DB_NAME}-${TAG}, kind: Service}]"
    spec:
      ports:
        - name: ${NAME}-${TAG}-tcp
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}
        environment: ${TAG}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}
        environment: ${TAG}
        role: ${ROLE}
      annotations:
        haproxy.router.openshift.io/ip_whitelist: ${ALLOW_LIST}
    spec:
      host: ${APPLICATION_DOMAIN}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      port:
        targetPort: ${NAME}-${TAG}-tcp
      to:
        kind: Service
        name: ${NAME}-${TAG}
        weight: 100

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}
        environment: ${TAG}
        role: ${ROLE}
      annotations:
        description: Defines how to deploy the application server
    spec:
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          pre:
            execNewPod:
              command:
                - /opt/app-root/pre-hook-update-db.sh
              containerName: ${NAME}-${TAG}
            failurePolicy: Abort
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-${TAG}
            from:
              kind: ImageStreamTag
              namespace: ${NAMESPACE}-${IMAGE_NAMESPACE}
              name: ${NAME}:${TAG}
      replicas: 1
      selector:
        name: ${NAME}
        environment: ${TAG}
      template:
        metadata:
          name: ${NAME}-${TAG}
          labels:
            name: ${NAME}
            environment: ${TAG}
            role: ${ROLE}
        spec:
          containers:
            - name: ${NAME}-${TAG}
              image: ${IMAGE_REGISTRY}/${NAMESPACE}-${IMAGE_NAMESPACE}/${NAME}:${TAG}
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 3
                timeoutSeconds: 30
                httpGet:
                  path: /ops/readyz
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 120
                timeoutSeconds: 30
                httpGet:
                  path: /ops/healthz
                  port: 8080

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}
        environment: ${TAG}
        role: ${ROLE}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${NAME}-${TAG}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: legal-api

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: api

  - name: NAMESPACE
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: cc892f

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: tools

  - name: IMAGE_REGISTRY
    displayName: Image Registry
    required: true
    description: The image registry of the OpenShift project.
    value: image-registry.openshift-image-registry.svc:5000

  - name: DB_NAME
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: postgresql

  - name: APPLICATION_DOMAIN
    displayName: Application Domain
    description: The endpoint used for routing access to the application.
    value: legal-api-dev.apps.silver.devops.gov.bc.ca

  - name: ALLOW_LIST
    displayName: Allow List
    description: The allow list containing all of the trusted source IPs.
    required: false

  - name: MIN_REPLICAS
    displayName: Minimum Replicas
    description: The minimum number of pods to have running.
    required: true
    value: "1"

  - name: MAX_REPLICAS
    displayName: Maximum Replicas
    description: The maximum number of pods to have running.
    required: true
    value: "1"

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m

  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi

  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
