apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tools-jenkins-image-puller-rbac
objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: jenkins-image-puller
      namespace: cc892f-tools
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:image-puller
    subjects:
      - kind: ServiceAccount
        name: builder
        namespace: cc892f-dev
      - kind: ServiceAccount
        name: builder
        namespace: cc892f-dev
      - kind: ServiceAccount
        name: builder
        namespace: cc892f-test
      - kind: ServiceAccount
        name: builder
        namespace: cc892f-prod
