apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-04-08T16:11:47Z'
  generation: 31
  labels:
    app: oradb1
  name: oradb1
  namespace: gl2uos-tools
  resourceVersion: '729334451'
  selfLink: /apis/apps.openshift.io/v1/namespaces/gl2uos-tools/deploymentconfigs/oradb1
  uid: 02646fbe-5a19-11e9-9558-0050568379a2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: oradb1
    deploymentconfig: oradb1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: oradb1
        deploymentconfig: oradb1
    spec:
      containers:
        - env:
            - name: ORACLE_PDB
              value: oracle1
            - name: ORACLE_SID
              value: ORCLCDB
          image: >-
            docker-registry.default.svc:5000/gl2uos-tools/oradb1@sha256:6d8e8dcd979d0da41a412a75e9182e8db053798aba81b6d2f2a5e07c40167387
          imagePullPolicy: Always
          name: oradb1
          ports:
            - containerPort: 1521
              protocol: TCP
            - containerPort: 5500
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 8Gi
          securityContext:
            runAsUser: 1003919999
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /import
              name: dumpfile
            - mountPath: /ORCL
              name: orcl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
          - 0
          - 54321
          - 54322
      terminationGracePeriodSeconds: 30
      volumes:
        - name: dumpfile
          persistentVolumeClaim:
            claimName: importoradb
        - name: orcl
          persistentVolumeClaim:
            claimName: oradb
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - oradb1
        from:
          kind: ImageStreamTag
          name: 'oradb1:latest'
          namespace: gl2uos-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/gl2uos-tools/oradb1@sha256:6d8e8dcd979d0da41a412a75e9182e8db053798aba81b6d2f2a5e07c40167387
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-04-08T17:45:44Z'
      lastUpdateTime: '2019-04-08T17:45:44Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-04-08T20:05:17Z'
      lastUpdateTime: '2019-04-08T20:05:20Z'
      message: replication controller "oradb1-13" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/gl2uos-tools/oradb1@sha256:6d8e8dcd979d0da41a412a75e9182e8db053798aba81b6d2f2a5e07c40167387
        type: ImageChange
    message: image change
  latestVersion: 13
  observedGeneration: 31
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
