[tool.poetry]
name = "email-reminder"
version = "0.1.0"
description = "Email reminder job"
authors = ["Hongjing Chen <Hongjing.Chen@gov.bc.ca>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.3.2"
Flask-Moment = "^1.0.5"
Flask-Script = "^2.0.6"
Jinja2 = "^3.1.2"
MarkupSafe = "^2.1.3"
Werkzeug = "^2.3.7"
aniso8601 = "^9.0.1"
attrs = "^23.1.0"
blinker = "^1.6.2"
certifi = "^2023.7.22"
click = "^8.1.6"
ecdsa = "^0.18.0"
flask-jwt-oidc = "^0.3.0"
gunicorn = "^20.1.0"
itsdangerous = "^2.1.2"
jsonschema = "^4.19.0"
pyasn1 = "^0.5.0"
pyrsistent = "^0.19.3"
python-dotenv = "^1.0.0"
python-jose = "^3.3.0"
pytz = "^2023.3"
rsa = "^4.9"
sentry-sdk = "^1.29.2"
six = "^1.16.0"
urllib3 = "^1.22.0"
legal_api = { git = "https://github.com/bcgov/lear.git", subdirectory = "legal-api", branch = "feature-legal-name" }
registry-schemas = {git = "https://github.com/bcgov/business-schemas.git", branch = "feature-legal-name"}
simple_cloudevent = { git = "https://github.com/daxiom/simple-cloudevent.py" }
google-auth = "^2.21.0"
google-cloud-pubsub = "^2.17.1"
pg8000 = "^1.29.8"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-mock = "^3.11.1"
black = "^23.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
pylint = "^3.0.3"
bandit = "^1.7.6"
flake8-pyproject = "^1.2.3"
isort = "^5.13.2"

[tool.bandit]
exclude_dirs = [".venv","tests"]
skips = ["B104"]

[tool.flake8]
ignore = ["F401","E402", "Q000", "E203", "W503", "W504" ]
exclude = [
    ".venv",
    ".git",
    "*migrations*"
]
per-file-ignores = [
    "__init__.py:F401",
    "*.py:B902"
]
max-line-length = 120
docstring-min-length=10
count = true

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
ignore = [ "migrations", "test"]
notes = ["FIXME","XXX","TODO"]
ignored-modules= ["flask_sqlalchemy", "sqlalchemy", "SQLAlchemy" , "alembic", "scoped_session"]
ignored-classes= "scoped_session"
disable = "C0209,C0301,W0511,W0613,W0703,W1514,R0801,R0902,R0903,R0911,R0401,R1705,R1718,W3101"
extension-pkg-whitelist = "pydantic"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
