-- -- Disable triggers for corp-scoped tables (subset refresh/load).
-- -- Intended to be executed from a master DbSchemaCLI script while connected to the target Postgres DB.

-- ALTER TABLE corporation DISABLE TRIGGER ALL;
-- ALTER TABLE corp_name DISABLE TRIGGER ALL;
-- ALTER TABLE corp_state DISABLE TRIGGER ALL;
-- ALTER TABLE event DISABLE TRIGGER ALL;
-- ALTER TABLE filing DISABLE TRIGGER ALL;
-- ALTER TABLE filing_user DISABLE TRIGGER ALL;
-- ALTER TABLE office DISABLE TRIGGER ALL;
-- ALTER TABLE corp_comments DISABLE TRIGGER ALL;
-- ALTER TABLE ledger_text DISABLE TRIGGER ALL;
-- ALTER TABLE corp_party DISABLE TRIGGER ALL;
-- ALTER TABLE corp_party_relationship DISABLE TRIGGER ALL;
-- ALTER TABLE offices_held DISABLE TRIGGER ALL;
-- ALTER TABLE completing_party DISABLE TRIGGER ALL;
-- ALTER TABLE submitting_party DISABLE TRIGGER ALL;
-- ALTER TABLE corp_flag DISABLE TRIGGER ALL;
-- ALTER TABLE cont_out DISABLE TRIGGER ALL;
-- ALTER TABLE conv_event DISABLE TRIGGER ALL;
-- ALTER TABLE conv_ledger DISABLE TRIGGER ALL;
-- ALTER TABLE corp_involved_amalgamating DISABLE TRIGGER ALL;
-- ALTER TABLE corp_involved_cont_in DISABLE TRIGGER ALL;
-- ALTER TABLE corp_restriction DISABLE TRIGGER ALL;
-- ALTER TABLE correction DISABLE TRIGGER ALL;
-- ALTER TABLE jurisdiction DISABLE TRIGGER ALL;
-- ALTER TABLE resolution DISABLE TRIGGER ALL;
-- ALTER TABLE share_series DISABLE TRIGGER ALL;
-- ALTER TABLE share_struct DISABLE TRIGGER ALL;
-- ALTER TABLE share_struct_cls DISABLE TRIGGER ALL;
-- ALTER TABLE notification DISABLE TRIGGER ALL;
-- ALTER TABLE notification_resend DISABLE TRIGGER ALL;
-- ALTER TABLE party_notification DISABLE TRIGGER ALL;
-- ALTER TABLE payment DISABLE TRIGGER ALL;
-- ALTER TABLE carsfile DISABLE TRIGGER ALL;
-- ALTER TABLE carsbox DISABLE TRIGGER ALL;
-- ALTER TABLE carsrept DISABLE TRIGGER ALL;
-- ALTER TABLE carindiv DISABLE TRIGGER ALL;

ALTER TABLE TARGET_SCHEMA.notification 
  DROP CONSTRAINT fk_notification_filing ;
ALTER TABLE TARGET_SCHEMA.office 
  DROP CONSTRAINT fk_office_mailing_address ;
ALTER TABLE TARGET_SCHEMA.office 
DROP CONSTRAINT fk_office_delivery_address ;
ALTER TABLE TARGET_SCHEMA.corp_party 
  DROP CONSTRAINT fk_corp_party_mailing_address ;
ALTER TABLE TARGET_SCHEMA.completing_party 
  DROP CONSTRAINT fk_completing_party_address ;
ALTER TABLE TARGET_SCHEMA.office 
  DROP CONSTRAINT fk_corp_party_delivery_address ;
ALTER TABLE TARGET_SCHEMA.notification 
  DROP CONSTRAINT fk_notification_address ;
ALTER TABLE TARGET_SCHEMA.corp_processing 
  DROP CONSTRAINT fk_corp_processing_corporation ;
ALTER TABLE TARGET_SCHEMA.colin_tracking 
  DROP CONSTRAINT fk_colin_tracking_corporation ;
ALTER TABLE TARGET_SCHEMA.filing ALTER COLUMN arrangement_ind TYPE CHARACTER VARYING(255);
ALTER TABLE TARGET_SCHEMA.corporation ALTER COLUMN send_ar_ind TYPE CHARACTER VARYING(255);
ALTER TABLE TARGET_SCHEMA.share_series ALTER COLUMN max_share_ind TYPE CHARACTER VARYING(255);
ALTER TABLE TARGET_SCHEMA.share_struct_cls ALTER COLUMN max_share_ind TYPE CHARACTER VARYING(255);
ALTER TABLE TARGET_SCHEMA.filing ALTER COLUMN court_appr_ind TYPE CHARACTER VARYING(255);
ALTER TABLE TARGET_SCHEMA.share_struct_cls ALTER COLUMN spec_rights_ind TYPE CHARACTER VARYING(255);
ALTER TABLE TARGET_SCHEMA.share_struct_cls ALTER COLUMN par_value_ind TYPE CHARACTER VARYING(255);

