-- Enable triggers for corp-scoped tables (subset refresh/load).
-- Intended to be executed from a master DbSchemaCLI script while connected to the target Postgres DB.

ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corporation ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_name ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_state ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.event ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.filing ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.filing_user ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.office ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_comments ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.ledger_text ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_party ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_party_relationship ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.offices_held ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.completing_party ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.submitting_party ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_flag ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.cont_out ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.conv_event ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.conv_ledger ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_involved_amalgamating ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_involved_cont_in ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_restriction ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.correction ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.jurisdiction ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.resolution ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.share_series ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.share_struct ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.share_struct_cls ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.notification ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.notification_resend ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.party_notification ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.payment ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carsfile ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carsbox ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carsrept ENABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carindiv ENABLE TRIGGER ALL;
