-- Disable triggers for corp-scoped tables (subset refresh/load).
-- Intended to be executed from a master DbSchemaCLI script while connected to the target Postgres DB.

ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corporation DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_name DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_state DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.event DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.filing DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.filing_user DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.office DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_comments DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.ledger_text DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_party DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_party_relationship DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.offices_held DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.completing_party DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.submitting_party DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_flag DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.cont_out DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.conv_event DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.conv_ledger DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_involved_amalgamating DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_involved_cont_in DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.corp_restriction DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.correction DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.jurisdiction DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.resolution DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.share_series DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.share_struct DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.share_struct_cls DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.notification DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.notification_resend DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.party_notification DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.payment DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carsfile DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carsbox DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carsrept DISABLE TRIGGER ALL;
ALTER TABLE __DBSCHEMA_TARGET_SCHEMA__.carindiv DISABLE TRIGGER ALL;
