"""request-tracker-admin

Revision ID: 0b2af7f762bb
Revises: 285e11a8f0c4
Create Date: 2022-07-04 16:28:03.375711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b2af7f762bb'
down_revision = '285e11a8f0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_tracker', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('request_tracker', sa.Column('message_id', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_tracker', 'message_id')
    op.drop_column('request_tracker', 'is_admin')
    # ### end Alembic commands ###
