"""Change resolutions field to text field, 
   that way we can put in more text than 4096, which is very limiting for HTML.

Revision ID: 0c792224fe11
Revises: 7e02a91ac3c6
Create Date: 2023-05-01 09:44:40.996934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c792224fe11'
down_revision = '7e02a91ac3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resolutions', 'resolution',
            existing_type=sa.VARCHAR(length=4096),
            type_=sa.Text(),
            existing_nullable=True,
            autoincrement=False)
    op.alter_column('resolutions_version', 'resolution',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.Text(),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resolutions', 'resolution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('resolutions_version', 'resolution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
