"""empty message

Revision ID: 0fb2ae5711ed
Revises: 176f983485c8
Create Date: 2019-10-03 13:49:12.619681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb2ae5711ed'
down_revision = '176f983485c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('mailing_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'directors', 'addresses', ['mailing_address_id'], ['id'])
    op.add_column('directors_version', sa.Column('mailing_address_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directors_version', 'mailing_address_id')
    op.drop_constraint(None, 'directors', type_='foreignkey')
    op.drop_column('directors', 'mailing_address_id')
    # ### end Alembic commands ###
