"""request-tracker-change

Revision ID: 1400cc212014
Revises: 86d8aca36208
Create Date: 2022-05-04 14:49:00.080835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1400cc212014'
down_revision = '86d8aca36208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_tracker', sa.Column('filing_id', sa.Integer(), nullable=True))
    
    op.execute('''
        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE VARCHAR(25);

        DROP TYPE request_tracker_type;
        
        CREATE TYPE request_tracker_type AS ENUM ('INFORM_CRA', 'GET_BN', 'CHANGE_STATUS', 'CHANGE_NAME', 'CHANGE_DELIVERY_ADDRESS', 'CHANGE_MAILING_ADDRESS');

        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE request_tracker_type USING (request_type::request_tracker_type);
    ''')
        
    op.create_index(op.f('ix_request_tracker_business_id'), 'request_tracker', ['business_id'], unique=False)
    op.create_index(op.f('ix_request_tracker_filing_id'), 'request_tracker', ['filing_id'], unique=False)
    op.create_foreign_key('request_tracker_filing_id_fkey', 'request_tracker', 'filings', ['filing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('request_tracker_filing_id_fkey', 'request_tracker', type_='foreignkey')

    op.drop_index(op.f('ix_request_tracker_filing_id'), table_name='request_tracker')
    op.drop_index(op.f('ix_request_tracker_business_id'), table_name='request_tracker')
    
    op.execute('''
        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE VARCHAR(25);

        DROP TYPE request_tracker_type;
        
        CREATE TYPE request_tracker_type AS ENUM ('INFORM_CRA', 'GET_BN');

        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE request_tracker_type USING (request_type::request_tracker_type);
    ''')
    
    op.drop_column('request_tracker', 'filing_id')
    # ### end Alembic commands ###
