"""amalgamations_version and amalgamating_businesses_version

Revision ID: 146e135484b2
Revises: ba862cfda9e5
Create Date: 2024-03-04 11:52:54.691924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '146e135484b2'
down_revision = 'ba862cfda9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('amalgamation', 'amalgamations')
    op.rename_table('amalgamating_business', 'amalgamating_businesses')

    op.create_table(
        'amalgamations_version',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('business_id', sa.Integer(), nullable=False),
        sa.Column('filing_id', sa.Integer(), nullable=False),
        sa.Column('amalgamation_date', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('amalgamation_type', postgresql.ENUM(name='amalgamation_type', create_type=False), nullable=False),
        sa.Column('court_approval', sa.Boolean(), nullable=False),
        sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['filing_id'], ['filings.id']),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id']),
        sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_amalgamations_version_end_transaction_id'), 'amalgamations_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_business_id'), 'amalgamations_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_filing_id'), 'amalgamations_version', ['filing_id'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_operation_type'), 'amalgamations_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_transaction_id'), 'amalgamations_version', ['transaction_id'], unique=False)

    op.create_table(
        'amalgamating_businesses_version',
        sa.Column('id', sa.Integer(), primary_key=False),
        sa.Column('business_id', sa.Integer(), nullable=True),
        sa.Column('amalgamation_id', sa.Integer(), nullable=False),
        sa.Column('role', postgresql.ENUM(name='amalgamating_business_role', create_type=False), nullable=False),
        sa.Column('foreign_jurisdiction', sa.String(length=10), nullable=True),
        sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True),
        sa.Column('foreign_name', sa.String(length=100), nullable=True),
        sa.Column('foreign_identifier', sa.String(length=50), nullable=True),
        sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id']),
        sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_amalgamating_businesses_version_end_transaction_id'), 'amalgamating_businesses_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_business_id'), 'amalgamating_businesses_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_amalgamation_id'), 'amalgamating_businesses_version', ['amalgamation_id'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_operation_type'), 'amalgamating_businesses_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_transaction_id'), 'amalgamating_businesses_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('amalgamations', 'amalgamation')
    op.rename_table('amalgamating_businesses', 'amalgamating_business')
    op.drop_table('amalgamating_businesses_version')
    op.drop_table('amalgamations_version')
    # ### end Alembic commands ###
