"""empty message

Revision ID: 176f983485c8
Revises: 5ad3243edc3e
Create Date: 2019-09-11 19:11:54.190918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176f983485c8'
down_revision = '5ad3243edc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('legal_type', sa.String(length=10), nullable=True))
    op.add_column('businesses_version', sa.Column('legal_type', sa.String(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'legal_type')
    op.drop_column('businesses', 'legal_type')
    # ### end Alembic commands ###
