"""add_idp_userid_to_users

Revision ID: 1ba027b074a5
Revises: e10f724fad6d
Create Date: 2022-11-22 12:44:50.751121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba027b074a5'
down_revision = 'e10f724fad6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idp_userid', sa.String(length=256)))
    #op.drop_constraint('users_sub_key', 'users', type_='unique')
    #op.create_unique_constraint('users_idp_userid_key', 'users', ['idp_userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('users_sub_key', 'users', ['sub'])
    #op.drop_constraint('users_idp_userid_key', 'users', ['idp_userid'])
    op.drop_column('users', 'idp_userid')
    # ### end Alembic commands ###
