"""connection_app_attestation

Revision ID: 201e34168903
Revises: d9254d3cbbf4
Create Date: 2025-02-27 00:52:44.233035

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '201e34168903'
down_revision = '24b59f535ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dc_connections', sa.Column(
        'is_attested',  sa.Boolean, default=False))
    op.add_column('dc_connections', sa.Column(
        'last_attested', sa.DateTime, default=None))
    op.execute(
        'UPDATE dc_connections SET connection_state = \'invitation-sent\' WHERE connection_state = \'invitation\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'UPDATE dc_connections SET connection_state = \'invitation\' WHERE connection_state = \'invitation-sent\'')
    op.drop_column('dc_connections', 'is_attested')
    op.drop_column('dc_connections', 'last_attested')
    # ### end Alembic commands ###
