"""empty message

Revision ID: 2467e09986f2
Revises: 4a27dc3cf7bc
Create Date: 2026-03-05 10:14:34.122569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2467e09986f2'
down_revision = '4a27dc3cf7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('last_lr_year', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('in_liquidation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses_version', sa.Column('last_lr_year', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('businesses_version', sa.Column('in_liquidation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'in_liquidation_date')
    op.drop_column('businesses_version', 'last_lr_year')
    op.drop_column('businesses', 'in_liquidation_date')
    op.drop_column('businesses', 'last_lr_year')
    # ### end Alembic commands ###
