"""party-role-relationship

Revision ID: 2e29ebe9a830
Revises: 2afccb4603ec
Create Date: 2023-01-30 13:26:33.708772

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2e29ebe9a830'
down_revision = '2afccb4603ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_role_relationships_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('relationship_type', sa.String(length=30), autoincrement=False, nullable=False),
    sa.Column('party_role_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_party_role_relationships_version_end_transaction_id'), 'party_role_relationships_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_party_role_relationships_version_operation_type'), 'party_role_relationships_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_party_role_relationships_version_transaction_id'), 'party_role_relationships_version', ['transaction_id'], unique=False)
    op.create_table('party_role_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('party_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_role_id'], ['party_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('parties', 'tax_id')
    op.drop_column('parties_version', 'tax_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties_version', sa.Column('tax_id', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('parties', sa.Column('tax_id', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_table('party_role_relationships')
    op.drop_index(op.f('ix_party_role_relationships_version_transaction_id'), table_name='party_role_relationships_version')
    op.drop_index(op.f('ix_party_role_relationships_version_operation_type'), table_name='party_role_relationships_version')
    op.drop_index(op.f('ix_party_role_relationships_version_end_transaction_id'), table_name='party_role_relationships_version')
    op.drop_table('party_role_relationships_version')
    # ### end Alembic commands ###
