"""empty message

Revision ID: 2e986c1d4de6
Revises: a8f42b830d86
Create Date: 2020-07-14 11:22:56.573234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e986c1d4de6'
down_revision = 'a8f42b830d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('restriction_ind', sa.Boolean(), nullable=True))
    op.add_column('businesses_version', sa.Column('restriction_ind', sa.Boolean(), autoincrement=False, nullable=True))

    update_restriction_ind = 'update businesses set restriction_ind=false where restriction_ind is null'
    op.execute(update_restriction_ind)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'restriction_ind')
    op.drop_column('businesses', 'restriction_ind')
    # ### end Alembic commands ###
