"""empty message

Revision ID: 361b51b824c0
Revises: ad3ef106696c
Create Date: 2020-02-27 11:43:05.647252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361b51b824c0'
down_revision = 'ad3ef106696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filings', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filings', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
