"""empty message

Revision ID: 441a5e6cf682
Revises: 176f983485c8
Create Date: 2019-10-07 14:29:20.672641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData


# revision identifiers, used by Alembic.
revision = '441a5e6cf682'
down_revision = '176f983485c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_types',
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('offices_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('office_type', sa.String(length=75), autoincrement=False, nullable=True),
    sa.Column('deactivated_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_offices_version_business_id'), 'offices_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_offices_version_end_transaction_id'), 'offices_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_offices_version_operation_type'), 'offices_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_offices_version_transaction_id'), 'offices_version', ['transaction_id'], unique=False)
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_type', sa.String(length=75), nullable=True),
    sa.Column('deactivated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['office_type'], ['office_types.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_business_id'), 'offices', ['business_id'], unique=False)
    op.add_column('addresses', sa.Column('office_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'offices', ['office_id'], ['id'])
    op.add_column('addresses_version', sa.Column('office_id', sa.Integer(), autoincrement=False, nullable=True))

    meta = MetaData(bind=op.get_bind())
    meta.reflect(only=('office_types',))
    
    office_types_table = Table('office_types', meta)

    op.bulk_insert(
        office_types_table,
        [
            {
                'identifier':'registeredOffice', 'description':'Registered Office'
            },
            {
                'identifier':'recordsOffice', 'description':'Records Office'
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses_version', 'office_id')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'office_id')
    op.drop_index(op.f('ix_offices_business_id'), table_name='offices')
    op.drop_table('offices')
    op.drop_index(op.f('ix_offices_version_transaction_id'), table_name='offices_version')
    op.drop_index(op.f('ix_offices_version_operation_type'), table_name='offices_version')
    op.drop_index(op.f('ix_offices_version_end_transaction_id'), table_name='offices_version')
    op.drop_index(op.f('ix_offices_version_business_id'), table_name='offices_version')
    op.drop_table('offices_version')
    op.drop_table('office_types')
    # ### end Alembic commands ###
