"""empty message

Revision ID: 442829649a2a
Revises: c17d77b30bdb
Create Date: 2020-03-27 14:38:28.567013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442829649a2a'
down_revision = 'c17d77b30bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_classes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('par_value_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('par_value', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_share_classes_version_end_transaction_id'), 'share_classes_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_share_classes_version_name'), 'share_classes_version', ['name'], unique=False)
    op.create_index(op.f('ix_share_classes_version_operation_type'), 'share_classes_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_share_classes_version_transaction_id'), 'share_classes_version', ['transaction_id'], unique=False)
    op.create_table('share_series_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('share_class_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_share_series_version_end_transaction_id'), 'share_series_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_share_series_version_name'), 'share_series_version', ['name'], unique=False)
    op.create_index(op.f('ix_share_series_version_operation_type'), 'share_series_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_share_series_version_transaction_id'), 'share_series_version', ['transaction_id'], unique=False)
    op.create_table('share_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), nullable=True),
    sa.Column('max_shares', sa.Integer(), nullable=True),
    sa.Column('par_value_flag', sa.Boolean(), nullable=True),
    sa.Column('par_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_classes_name'), 'share_classes', ['name'], unique=False)
    op.create_table('share_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), nullable=True),
    sa.Column('max_shares', sa.Integer(), nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), nullable=True),
    sa.Column('share_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['share_class_id'], ['share_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_series_name'), 'share_series', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_series_name'), table_name='share_series')
    op.drop_table('share_series')
    op.drop_index(op.f('ix_share_classes_name'), table_name='share_classes')
    op.drop_table('share_classes')
    op.drop_index(op.f('ix_share_series_version_transaction_id'), table_name='share_series_version')
    op.drop_index(op.f('ix_share_series_version_operation_type'), table_name='share_series_version')
    op.drop_index(op.f('ix_share_series_version_name'), table_name='share_series_version')
    op.drop_index(op.f('ix_share_series_version_end_transaction_id'), table_name='share_series_version')
    op.drop_table('share_series_version')
    op.drop_index(op.f('ix_share_classes_version_transaction_id'), table_name='share_classes_version')
    op.drop_index(op.f('ix_share_classes_version_operation_type'), table_name='share_classes_version')
    op.drop_index(op.f('ix_share_classes_version_name'), table_name='share_classes_version')
    op.drop_index(op.f('ix_share_classes_version_end_transaction_id'), table_name='share_classes_version')
    op.drop_table('share_classes_version')
    # ### end Alembic commands ###
