"""empty message

Revision ID: 4ee6f0abb797
Revises: b826412a6a65
Create Date: 2019-06-17 10:06:29.846052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee6f0abb797'
down_revision = 'b826412a6a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colin_last_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_event_id')
    )
    op.add_column('filings', sa.Column('colin_event_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'colin_event_id')
    op.drop_table('colin_last_update')
    # ### end Alembic commands ###
