"""empty message

Revision ID: 4fd81e1bfbf0
Revises: 0fb2ae5711ed
Create Date: 2019-10-23 08:58:24.658127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd81e1bfbf0'
down_revision = '94c2a694d51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'effective_date')
    # ### end Alembic commands ###
