"""empty message

Revision ID: 5652df7736b8
Revises: 
Create Date: 2019-04-07 20:58:13.959299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5652df7736b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_name', sa.String(length=1000), nullable=True),
    sa.Column('founding_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('tax_id', sa.String(length=15), nullable=True),
    sa.Column('fiscal_year_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_identifier'), 'business', ['identifier'], unique=False)
    op.create_index(op.f('ix_business_legal_name'), 'business', ['legal_name'], unique=False)
    op.create_index(op.f('ix_business_tax_id'), 'business', ['tax_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('sub', sa.String(length=36), nullable=True),
    sa.Column('iss', sa.String(length=1024), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_business_tax_id'), table_name='business')
    op.drop_index(op.f('ix_business_legal_name'), table_name='business')
    op.drop_index(op.f('ix_business_identifier'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
