"""empty message

Revision ID: 5ad3243edc3e
Revises: 860bb6075dde
Create Date: 2019-08-09 15:49:03.983464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad3243edc3e'
down_revision = '860bb6075dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses_version', sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'last_ledger_timestamp')
    op.drop_column('businesses', 'last_ledger_timestamp')
    # ### end Alembic commands ###
