"""add_sent_to_gazette_table

Revision ID: 6ce7d2e74c5b
Revises: 3d8eb786f4c2
Create Date: 2021-11-10 12:09:37.801168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce7d2e74c5b'
down_revision = '3d8eb786f4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_to_gazette',
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=False),    
    sa.Column('sent_to_gazette_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('filing_id')
    )    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_table('sent_to_gazette')
    # ### end Alembic commands ###
