"""empty message

Revision ID: 7575af513efb
Revises: 1a8c89b722e2
Create Date: 2020-05-14 17:16:30.426205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7575af513efb'
down_revision = '1a8c89b722e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filings', 'payment_error_type', new_column_name='payment_status_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filings', 'payment_status_code', new_column_name='payment_error_type')
    # ### end Alembic commands ###
