"""empty message

Revision ID: 7c86cc916b5c
Revises: 52553d4d6309
Create Date: 2019-12-17 15:27:22.009335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c86cc916b5c'
down_revision = '52553d4d6309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('source', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###
    source_colin = 'update filings set source=\'COLIN\' where colin_event_id is not null or filing_type=\'lear_epoch\''
    op.execute(source_colin)

    source_lear = 'update filings set source=\'LEAR\' where colin_event_id is null and filing_type!=\'lear_epoch\''
    op.execute(source_lear)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'source')
    # ### end Alembic commands ###
