"""last_ar_reminder_year

Revision ID: 7e02a91ac3c6
Revises: 89fe33f436c1
Create Date: 2023-04-13 16:04:23.200797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e02a91ac3c6'
down_revision = '89fe33f436c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('last_ar_reminder_year', sa.Integer(), nullable=True))
    op.add_column('businesses_version', sa.Column('last_ar_reminder_year', sa.Integer(), autoincrement=False, nullable=True))
    op.execute('''
        UPDATE businesses SET last_ar_reminder_year=last_ar_year;
        UPDATE businesses_version SET last_ar_reminder_year=last_ar_year;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'last_ar_reminder_year')
    op.drop_column('businesses', 'last_ar_reminder_year')    
    # ### end Alembic commands ###
