"""empty message

Revision ID: 7f32f50daaac
Revises: c17d77b30bdb
Create Date: 2020-03-25 13:30:13.565737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f32f50daaac'
down_revision = 'c17d77b30bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_structure_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('share_type', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('par_value', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('special_rights', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_share_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_share_structure_version_end_transaction_id'), 'share_structure_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_share_structure_version_name'), 'share_structure_version', ['name'], unique=False)
    op.create_index(op.f('ix_share_structure_version_operation_type'), 'share_structure_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_share_structure_version_transaction_id'), 'share_structure_version', ['transaction_id'], unique=False)
    op.create_table('share_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_shares', sa.Integer(), nullable=True),
    sa.Column('par_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('special_rights', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('parent_share_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['parent_share_id'], ['share_structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_structure_name'), 'share_structure', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_structure_name'), table_name='share_structure')
    op.drop_table('share_structure')
    op.drop_index(op.f('ix_share_structure_version_transaction_id'), table_name='share_structure_version')
    op.drop_index(op.f('ix_share_structure_version_operation_type'), table_name='share_structure_version')
    op.drop_index(op.f('ix_share_structure_version_name'), table_name='share_structure_version')
    op.drop_index(op.f('ix_share_structure_version_end_transaction_id'), table_name='share_structure_version')
    op.drop_table('share_structure_version')
    # ### end Alembic commands ###
