"""empty message

Revision ID: 860bb6075dde
Revises: bf94a1b46804
Create Date: 2019-07-19 14:14:04.007871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860bb6075dde'
down_revision = 'bf94a1b46804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_directors_version_business_id'), 'directors_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_directors_version_end_transaction_id'), 'directors_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_directors_version_first_name'), 'directors_version', ['first_name'], unique=False)
    op.create_index(op.f('ix_directors_version_middle_initial'), 'directors_version', ['middle_initial'], unique=False)
    op.create_index(op.f('ix_directors_version_operation_type'), 'directors_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_directors_version_transaction_id'), 'directors_version', ['transaction_id'], unique=False)
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=1000), nullable=True),
    sa.Column('middle_initial', sa.String(length=1000), nullable=True),
    sa.Column('last_name', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_business_id'), 'directors', ['business_id'], unique=False)
    op.create_index(op.f('ix_directors_first_name'), 'directors', ['first_name'], unique=False)
    op.create_index(op.f('ix_directors_middle_initial'), 'directors', ['middle_initial'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directors_middle_initial'), table_name='directors')
    op.drop_index(op.f('ix_directors_first_name'), table_name='directors')
    op.drop_index(op.f('ix_directors_business_id'), table_name='directors')
    op.drop_table('directors')
    op.drop_index(op.f('ix_directors_version_transaction_id'), table_name='directors_version')
    op.drop_index(op.f('ix_directors_version_operation_type'), table_name='directors_version')
    op.drop_index(op.f('ix_directors_version_middle_initial'), table_name='directors_version')
    op.drop_index(op.f('ix_directors_version_first_name'), table_name='directors_version')
    op.drop_index(op.f('ix_directors_version_end_transaction_id'), table_name='directors_version')
    op.drop_index(op.f('ix_directors_version_business_id'), table_name='directors_version')
    op.drop_table('directors_version')
    # ### end Alembic commands ###
