"""add_restoration_approval_type_registrar_dates

Revision ID: 89fe33f436c1
Revises: 08da65c4a94a
Create Date: 2023-03-29 15:10:24.319173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fe33f436c1'
down_revision = '08da65c4a94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('application_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('filings', sa.Column('notice_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'application_date')
    op.drop_column('filings', 'notice_date')
    # ### end Alembic commands ###
