"""document-table

Revision ID: 8c74427a6c0e
Revises: b7c4b2533f84
Create Date: 2021-08-17 06:11:01.634099

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c74427a6c0e'
down_revision = 'b7c4b2533f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('file_key', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_business_id'), 'documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_documents_filing_id'), 'documents', ['filing_id'], unique=False)

    op.create_table('documents_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('file_key', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_documents_version_end_transaction_id'), 'documents_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_documents_version_business_id'), 'documents_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_documents_version_filing_id'), 'documents_version', ['filing_id'], unique=False)
    op.create_index(op.f('ix_documents_version_operation_type'), 'documents_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_documents_version_transaction_id'), 'documents_version', ['transaction_id'], unique=False)

    op.add_column('businesses', sa.Column('association_type', sa.String(length=50), nullable=True))
    op.add_column('businesses_version', sa.Column('association_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_filing_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_business_id'), table_name='documents')
    op.drop_table('documents')
    
    op.drop_index(op.f('ix_documents_version_end_transaction_id'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_business_id'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_filing_id'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_operation_type'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_transaction_id'), table_name='documents_version')
    op.drop_table('documents_version')

    op.drop_column('businesses_version', 'association_type')
    op.drop_column('businesses', 'association_type')
    # ### end Alembic commands ###
