"""empty message

Revision ID: 9147d4bc9939
Revises: da43f7bef692
Create Date: 2021-12-20 11:43:35.375689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9147d4bc9939'
down_revision = 'da43f7bef692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_roles', sa.Column('filing_id', sa.Integer(), nullable=True))
    op.add_column('party_roles_version', sa.Column('filing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'party_roles', 'filings', ['filing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party_roles', type_='foreignkey')
    op.drop_column('party_roles_version', 'filing_id')
    op.drop_column('party_roles', 'filing_id')
    # ### end Alembic commands ###
