"""empty message

Revision ID: 92c4974ce96f
Revises: 7c86cc916b5c
Create Date: 2020-01-23 14:53:39.298456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c4974ce96f'
down_revision = '7c86cc916b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colin_event_ids',
    sa.Column('colin_event_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('colin_event_id'),
    sa.UniqueConstraint('colin_event_id')
    )
    # ### end Alembic commands ###

    select_string = 'select colin_event_id, id from filings where colin_event_id is not null'
    conn = op.get_bind()
    query = conn.execute(select_string)

    ids_to_cross_reference = query.fetchall()
    for row in ids_to_cross_reference:
        colin_event_id = row[0]
        filing_id = row[1]
        op.execute(f'insert into colin_event_ids (colin_event_id, filing_id) values({colin_event_id}, {filing_id})')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'colin_event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('colin_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    select_string = 'select colin_event_id, filing_id from colin_event_ids'
    conn = op.get_bind()
    query = conn.execute(select_string)

    id_ref_dict = {}
    for id_ref in query.fetchall():
        colin_event_id = id_ref[0]
        filing_id = id_ref[1]
        # cant map multiple colin_event_ids to a single filing if downgrading
        if filing_id not in id_ref_dict:
            id_ref_dict[filing_id] = colin_event_id

    for filing_id in id_ref_dict:
        op.execute(f'update filings set colin_event_id={id_ref_dict[filing_id]} where id={filing_id}')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colin_event_ids')
    # ### end Alembic commands ###
