"""empty message

Revision ID: 94586877d4bc
Revises: 9147d4bc9939
Create Date: 2022-02-16 06:07:35

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94586877d4bc'
down_revision = '9147d4bc9939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update corp_types set full_desc='BC Sole Proprietorship' where corp_type_cd = 'SP'")
    op.execute("update corp_types set full_desc='BC General Partnership' where corp_type_cd = 'GP'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
