"""empty message

Revision ID: 94c2a694d51f
Revises: 176f983485c8
Create Date: 2019-10-11 14:10:05.542548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c2a694d51f'
down_revision = '0fb2ae5711ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('paper_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'paper_only')
    # ### end Alembic commands ###
