"""Extend postal code to match business schema spec.

Revision ID: a6e3fdc238dd
Revises: 0b2af7f762bb
Create Date: 2022-08-16 14:48:10.303433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e3fdc238dd'
down_revision = '0b2af7f762bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'postal_code',
                    existing_type=sa.VARCHAR(length=10),
                    type_=sa.String(length=15),
                    existing_nullable=True)

    op.alter_column('addresses_version', 'postal_code',
                    existing_type=sa.VARCHAR(length=10),
                    type_=sa.String(length=15),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'postal_code',
                    existing_type=sa.String(length=15),
                    type_=sa.VARCHAR(length=10),
                    existing_nullable=True)

    op.alter_column('addresses_version', 'postal_code',
                    existing_type=sa.String(length=15),
                    type_=sa.VARCHAR(length=10),
                    existing_nullable=True)
    # ### end Alembic commands ###
