"""empty message

Revision ID: a8f42b830d86
Revises: f3fb008e7b83
Create Date: 2020-07-13 12:20:29.951915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8f42b830d86'
down_revision = 'f3fb008e7b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolutions_version',
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('resolution_date', sa.Date(), autoincrement=False, nullable=False),
                    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
                    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    op.create_index(op.f('ix_resolutions_version_end_transaction_id'), 'resolutions_version', ['end_transaction_id'],
                    unique=False)
    op.create_index(op.f('ix_resolutions_version_operation_type'), 'resolutions_version', ['operation_type'],
                    unique=False)
    op.create_index(op.f('ix_resolutions_version_transaction_id'), 'resolutions_version', ['transaction_id'],
                    unique=False)

    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_resolutions_version_end_transaction_id'), table_name='resolutions_version')
    op.drop_index(op.f('ix_resolutions_version_operation_type'), table_name='resolutions_version')
    op.drop_index(op.f('ix_resolutions_version_transaction_id'), table_name='resolutions_version')
    op.drop_table('resolutions_version')
    # ### end Alembic commands ###
