"""add_furnishings_id_to_address

Revision ID: ac0065d92893
Revises: 01b28a2bb730
Create Date: 2024-07-08 07:49:30.435973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0065d92893'
down_revision = '01b28a2bb730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('furnishings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'furnishings', ['furnishings_id'], ['id'])
    op.add_column('addresses_version', sa.Column('furnishings_id', sa.Integer(), nullable=True))
    op.drop_column('furnishings', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'furnishings_id')
    op.drop_column('addresses_version', 'furnishings_id')
    op.add_column('furnishings', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'furnishings', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###
