"""empty message

Revision ID: ad21c1ed551e
Revises: d9254d3cbbf4
Create Date: 2025-02-21 14:05:14.971210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad21c1ed551e'
down_revision = 'd0b10576924c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('last_tr_year', sa.Integer(), nullable=True))
    op.add_column('businesses_version', sa.Column('last_tr_year', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'last_tr_year')
    op.drop_column('businesses', 'last_tr_year')
    # ### end Alembic commands ###
