"""empty message

Revision ID: ad3ef106696c
Revises: 1f01b9303b81
Create Date: 2020-02-25 11:48:24.035189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3ef106696c'
down_revision = '1f01b9303b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('parent_filing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filings', 'filings', ['parent_filing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filings', type_='foreignkey')
    op.drop_column('filings', 'parent_filing_id')
    # ### end Alembic commands ###
