"""continuation-out

Revision ID: ae43b5cc0d2d
Revises: 0c792224fe11
Create Date: 2023-05-24 13:55:32.504054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae43b5cc0d2d'
down_revision = '0c792224fe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('continuation_out_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True))
    op.add_column('businesses_version', sa.Column('continuation_out_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
    op.add_column('businesses_version', sa.Column('foreign_jurisdiction_region', sa.String(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'foreign_jurisdiction_region')
    op.drop_column('businesses_version', 'continuation_out_date')
    op.drop_column('businesses', 'foreign_jurisdiction_region')
    op.drop_column('businesses', 'continuation_out_date')
    # ### end Alembic commands ###
