"""empty message

Revision ID: b826412a6a65
Revises: 98ccc973c01d
Create Date: 2019-06-05 23:40:58.830880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b826412a6a65'
down_revision = '98ccc973c01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_business_id'), 'comments', ['business_id'], unique=False)
    op.create_index(op.f('ix_comments_staff_id'), 'comments', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_staff_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_business_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
