"""empty message

Revision ID: b9165c3187fc
Revises: 361b51b824c0
Create Date: 2020-03-17 11:14:17.143705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9165c3187fc'
down_revision = '361b51b824c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('party_type', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_parties_version_end_transaction_id'), 'parties_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_parties_version_first_name'), 'parties_version', ['first_name'], unique=False)
    op.create_index(op.f('ix_parties_version_middle_initial'), 'parties_version', ['middle_initial'], unique=False)
    op.create_index(op.f('ix_parties_version_operation_type'), 'parties_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_parties_version_transaction_id'), 'parties_version', ['transaction_id'], unique=False)
    op.create_table('party_roles_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('party_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_party_roles_version_end_transaction_id'), 'party_roles_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_party_roles_version_operation_type'), 'party_roles_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_party_roles_version_transaction_id'), 'party_roles_version', ['transaction_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('middle_initial', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_first_name'), 'parties', ['first_name'], unique=False)
    op.create_index(op.f('ix_parties_middle_initial'), 'parties', ['middle_initial'], unique=False)
    op.create_table('party_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_roles')
    op.drop_index(op.f('ix_parties_middle_initial'), table_name='parties')
    op.drop_index(op.f('ix_parties_first_name'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_party_roles_version_transaction_id'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_operation_type'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_end_transaction_id'), table_name='party_roles_version')
    op.drop_table('party_roles_version')
    op.drop_index(op.f('ix_parties_version_transaction_id'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_operation_type'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_middle_initial'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_first_name'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_end_transaction_id'), table_name='parties_version')
    op.drop_table('parties_version')
    # ### end Alembic commands ###
