"""foreign_corp_num_to_foreign_identifier

Revision ID: ba862cfda9e5
Revises: f978e34aa8bb
Create Date: 2024-01-30 09:50:49.159204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba862cfda9e5'
down_revision = 'f978e34aa8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amalgamating_business', 'foreign_corp_num', new_column_name='foreign_identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amalgamating_business', 'foreign_identifier', new_column_name='foreign_corp_num')
    # ### end Alembic commands ###
