"""cleanup-document-table

Revision ID: bf8d4391745e
Revises: bddd732a9269
Create Date: 2023-01-03 17:42:27.696030

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bf8d4391745e'
down_revision = 'bddd732a9269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents_version', 'content_type')
    op.drop_column('documents_version', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_version', sa.Column('file_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('documents_version', sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
