"""empty message

Revision ID: c17d77b30bdb
Revises: b9165c3187fc
Create Date: 2020-03-24 13:16:42.381717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c17d77b30bdb'
down_revision = 'b9165c3187fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_directors_version_business_id', table_name='directors_version')
    op.drop_index('ix_directors_version_end_transaction_id', table_name='directors_version')
    op.drop_index('ix_directors_version_first_name', table_name='directors_version')
    op.drop_index('ix_directors_version_middle_initial', table_name='directors_version')
    op.drop_index('ix_directors_version_operation_type', table_name='directors_version')
    op.drop_index('ix_directors_version_transaction_id', table_name='directors_version')
    op.drop_table('directors_version')
    op.drop_index('ix_directors_business_id', table_name='directors')
    op.drop_index('ix_directors_first_name', table_name='directors')
    op.drop_index('ix_directors_middle_initial', table_name='directors')
    op.drop_table('directors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('appointment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cessation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mailing_address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name='directors_address_id_fkey'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='directors_business_id_fkey'),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], name='directors_mailing_address_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='directors_pkey')
    )
    op.create_index('ix_directors_middle_initial', 'directors', ['middle_initial'], unique=False)
    op.create_index('ix_directors_first_name', 'directors', ['first_name'], unique=False)
    op.create_index('ix_directors_business_id', 'directors', ['business_id'], unique=False)
    op.create_table('directors_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('appointment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cessation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('mailing_address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='directors_version_pkey')
    )
    op.create_index('ix_directors_version_transaction_id', 'directors_version', ['transaction_id'], unique=False)
    op.create_index('ix_directors_version_operation_type', 'directors_version', ['operation_type'], unique=False)
    op.create_index('ix_directors_version_middle_initial', 'directors_version', ['middle_initial'], unique=False)
    op.create_index('ix_directors_version_first_name', 'directors_version', ['first_name'], unique=False)
    op.create_index('ix_directors_version_end_transaction_id', 'directors_version', ['end_transaction_id'], unique=False)
    op.create_index('ix_directors_version_business_id', 'directors_version', ['business_id'], unique=False)
    # ### end Alembic commands ###
