"""request-tracker-change-party

Revision ID: c212a141600c
Revises: 1400cc212014
Create Date: 2022-05-19 09:37:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c212a141600c'
down_revision = '1400cc212014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE VARCHAR(25);

        DROP TYPE request_tracker_type;
        
        CREATE TYPE request_tracker_type AS ENUM ('INFORM_CRA', 'GET_BN', 'CHANGE_STATUS', 'CHANGE_NAME', 'CHANGE_DELIVERY_ADDRESS', 'CHANGE_MAILING_ADDRESS', 'CHANGE_PARTY');

        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE request_tracker_type USING (request_type::request_tracker_type);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE VARCHAR(25);

        DROP TYPE request_tracker_type;
        
        CREATE TYPE request_tracker_type AS ENUM ('INFORM_CRA', 'GET_BN', 'CHANGE_STATUS', 'CHANGE_NAME', 'CHANGE_DELIVERY_ADDRESS', 'CHANGE_MAILING_ADDRESS');

        ALTER TABLE request_tracker ALTER COLUMN request_type TYPE request_tracker_type USING (request_type::request_tracker_type);
    ''')
    # ### end Alembic commands ###
