"""continuation-in

Revision ID: c4732cd8abfd
Revises: ef8f033d317b
Create Date: 2024-05-24 14:38:45.440604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4732cd8abfd'
down_revision = 'ef8f033d317b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continuation_ins',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
                    sa.Column('jurisdiction_region', sa.String(length=10), nullable=True),
                    sa.Column('identifier', sa.String(length=50), nullable=True),
                    sa.Column('legal_name', sa.String(length=1000), nullable=True),
                    sa.Column('tax_id', sa.String(length=15), nullable=True),
                    sa.Column('incorporation_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('expro_identifier', sa.String(length=50), nullable=True),
                    sa.Column('expro_legal_name', sa.String(length=1000), nullable=True),
                    sa.Column('business_id', sa.Integer(), nullable=False),
                    sa.Column('filing_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
                    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_continuation_ins_business_id'), 'continuation_ins', ['business_id'], unique=False)

    op.create_table('continuation_ins_version',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
                    sa.Column('jurisdiction_region', sa.String(length=10), nullable=True),
                    sa.Column('identifier', sa.String(length=50), nullable=True),
                    sa.Column('legal_name', sa.String(length=1000), nullable=True),
                    sa.Column('tax_id', sa.String(length=15), nullable=True),
                    sa.Column('incorporation_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('expro_identifier', sa.String(length=50), nullable=True),
                    sa.Column('expro_legal_name', sa.String(length=1000), nullable=True),
                    sa.Column('business_id', sa.Integer(), nullable=False),
                    sa.Column('filing_id', sa.Integer(), nullable=False),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['filing_id'], ['filings.id']),
                    sa.ForeignKeyConstraint(['business_id'], ['businesses.id']),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    op.create_index(op.f('ix_continuation_ins_version_end_transaction_id'), 'continuation_ins_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_continuation_ins_version_business_id'), 'continuation_ins_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_continuation_ins_version_operation_type'), 'continuation_ins_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_continuation_ins_version_transaction_id'), 'continuation_ins_version', ['transaction_id'], unique=False)

    op.drop_column('businesses', 'foreign_legal_type')
    op.drop_column('businesses', 'foreign_identifier')
    op.drop_column('businesses', 'foreign_incorporation_date')

    op.drop_column('businesses_version', 'foreign_legal_type')
    op.drop_column('businesses_version', 'foreign_identifier')
    op.drop_column('businesses_version', 'foreign_incorporation_date')

    op.add_column('documents', sa.Column('file_name', sa.String(length=1000), nullable=True))
    op.add_column('documents_version', sa.Column('file_name', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_version', 'file_name')
    op.drop_column('documents', 'file_name')

    op.add_column('businesses_version', sa.Column('foreign_incorporation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('businesses_version', sa.Column('foreign_identifier', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('businesses_version', sa.Column('foreign_legal_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    op.add_column('businesses', sa.Column('foreign_incorporation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('foreign_identifier', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('foreign_legal_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    op.drop_index(op.f('ix_continuation_ins_version_end_transaction_id'), table_name='continuation_ins_version')
    op.drop_index(op.f('ix_continuation_ins_version_business_id'), table_name='continuation_ins_version')
    op.drop_index(op.f('ix_continuation_ins_version_operation_type'), table_name='continuation_ins_version')
    op.drop_index(op.f('ix_continuation_ins_version_transaction_id'), table_name='continuation_ins_version')
    op.drop_table('continuation_ins_version')

    op.drop_index(op.f('ix_continuation_ins_business_id'), table_name='continuation_ins')
    op.drop_table('continuation_ins')
    # ### end Alembic commands ###
