"""add_send_ar_ind_to_businesses

Revision ID: d087a6ee9230
Revises: bf8d4391745e
Create Date: 2023-01-19 06:36:52.729122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd087a6ee9230'
down_revision = 'bf8d4391745e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('send_ar_ind', sa.Boolean(), autoincrement=False, server_default='True'))
    op.add_column('businesses_version', sa.Column('send_ar_ind', sa.Boolean(), autoincrement=False, server_default='True'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'send_ar_ind')
    op.drop_column('businesses_version', 'send_ar_ind')
    # ### end Alembic commands ###
