"""add_incomplete_business_info_column

Revision ID: d60927e1d53f
Revises: 86d8aca36208
Create Date: 2022-05-05 12:04:41.528009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60927e1d53f'
down_revision = '86d8aca36208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('incomplete_business_info', sa.Boolean(), nullable=True))
    op.add_column('businesses_version', sa.Column('incomplete_business_info', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'incomplete_business_info')
    op.drop_column('businesses', 'incomplete_business_info')
    # ### end Alembic commands ###
