"""add_sent_to_gazette

Revision ID: d9e21a1b82ca
Revises: e6ff12b18bef
Create Date: 2021-11-10 21:29:51.135585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e21a1b82ca'
down_revision = 'e6ff12b18bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_to_gazette',
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=False),    
    sa.Column('sent_to_gazette_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('filing_id')
    )    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_table('sent_to_gazette')
    # ### end Alembic commands ###
