"""empty message

Revision ID: da43f7bef692
Revises: d9e21a1b82ca
Create Date: 2021-12-09 15:15:34.439924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da43f7bef692'
down_revision = 'd9e21a1b82ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    state = postgresql.ENUM('ACTIVE', 'HISTORICAL', 'LIQUIDATION', name='state')
    state.create(op.get_bind(), checkfirst=True)
    op.add_column('businesses', sa.Column('state', state, nullable=True))
    op.add_column('businesses', sa.Column('admin_freeze', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('state_filing_id', sa.Integer(), nullable=True))
    op.add_column('businesses_version', sa.Column('state', state, nullable=True))
    op.add_column('businesses_version', sa.Column('admin_freeze', sa.Boolean(), nullable=True))
    op.add_column('businesses_version', sa.Column('state_filing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'filings', ['state_filing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses_version', 'state_filing_id')
    op.drop_column('businesses_version', 'admin_freeze')
    op.drop_column('businesses_version', 'state')
    op.drop_column('businesses', 'state_filing_id')
    op.drop_column('businesses', 'admin_freeze')
    op.drop_column('businesses', 'state')
    op.execute("DROP TYPE state;")
    # ### end Alembic commands ###
