"""add_indexes_for_business_and_task_endpoint_perf_tweaks

Revision ID: e10f724fad6d
Revises: ecfeee53451a
Create Date: 2022-09-23 12:19:52.047276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10f724fad6d'
down_revision = 'ecfeee53451a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # filings table
    op.create_index(op.f('ix_filings_business_id'), 'filings', ['business_id'], unique=False)
    op.create_index(op.f('ix_filings_filing_type'), 'filings', ['filing_type'], unique=False)
    op.create_index(op.f('ix_filings_status'), 'filings', ['status'], unique=False)
    op.create_index(op.f('ix_filings_submitter_id'), 'filings', ['submitter_id'], unique=False)

    # offices/offices_version table
    op.create_index(op.f('ix_offices_office_type'), 'offices', ['office_type'], unique=False)
    op.create_index(op.f('ix_offices_version_office_type'), 'offices_version', ['office_type'], unique=False)

    # addresses/addresses_version table
    op.create_index(op.f('ix_addresses_office_id'), 'addresses', ['office_id'], unique=False)
    op.create_index(op.f('ix_addresses_version_office_id'), 'addresses_version', ['office_id'], unique=False)

    # party_roles/party_roles_version table
    op.create_index(op.f('ix_party_roles_business_id'), 'party_roles', ['business_id'], unique=False)
    op.create_index(op.f('ix_party_roles_filing_id'), 'party_roles', ['filing_id'], unique=False)
    op.create_index(op.f('ix_party_roles_party_id'), 'party_roles', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_roles_role'), 'party_roles', ['role'], unique=False)
    op.create_index(op.f('ix_party_roles_version_business_id'), 'party_roles_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_party_roles_version_filing_id'), 'party_roles_version', ['filing_id'], unique=False)
    op.create_index(op.f('ix_party_roles_version_party_id'), 'party_roles_version', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_roles_version_role'), 'party_roles_version', ['role'], unique=False)

    # parties/parties_version table
    op.create_index(op.f('ix_parties_party_type'), 'parties', ['party_type'], unique=False)
    op.create_index(op.f('ix_parties_last_name'), 'parties', ['last_name'], unique=False)
    op.create_index(op.f('ix_parties_organization_name'), 'parties', ['organization_name'], unique=False)
    op.create_index(op.f('ix_parties_identifier'), 'parties', ['identifier'], unique=False)
    op.create_index(op.f('ix_parties_email'), 'parties', ['email'], unique=False)
    op.create_index(op.f('ix_parties_delivery_address_id'), 'parties', ['delivery_address_id'], unique=False)
    op.create_index(op.f('ix_parties_mailing_address_id'), 'parties', ['mailing_address_id'], unique=False)
    op.create_index(op.f('ix_parties_version_party_type'), 'parties_version', ['party_type'], unique=False)
    op.create_index(op.f('ix_parties_version_last_name'), 'parties_version', ['last_name'], unique=False)
    op.create_index(op.f('ix_parties_version_organization_name'), 'parties_version', ['organization_name'], unique=False)
    op.create_index(op.f('ix_parties_version_identifier'), 'parties_version', ['identifier'], unique=False)
    op.create_index(op.f('ix_parties_version_email'), 'parties_version', ['email'], unique=False)
    op.create_index(op.f('ix_parties_version_delivery_address_id'), 'parties_version', ['delivery_address_id'], unique=False)
    op.create_index(op.f('ix_parties_version_mailing_address_id'), 'parties_version', ['mailing_address_id'], unique=False)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # filings table
    op.drop_index(op.f('ix_filings_business_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_filing_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_status'), table_name='filings')
    op.drop_index(op.f('ix_filings_submitter_id'), table_name='filings')

    # offices/offices_version table
    op.drop_index(op.f('ix_offices_office_type'), table_name='offices')
    op.drop_index(op.f('ix_offices_version_office_type'), table_name='offices_version')

    # addresses/addresses_version table
    op.drop_index(op.f('ix_addresses_office_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_version_office_id'), table_name='addresses_version')

    # party_roles/party_roles_version table
    op.drop_index(op.f('ix_party_roles_business_id'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_filing_id'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_party_id'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_role'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_version_business_id'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_filing_id'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_party_id'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_role'), table_name='party_roles_version')

    # parties/parties_version table
    op.drop_index(op.f('ix_parties_party_type'), table_name='parties')
    op.drop_index(op.f('ix_parties_last_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_organization_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_identifier'), table_name='parties')
    op.drop_index(op.f('ix_parties_email'), table_name='parties')
    op.drop_index(op.f('ix_parties_delivery_address_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_mailing_address_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_version_party_type'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_last_name'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_organization_name'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_identifier'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_email'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_delivery_address_id'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_mailing_address_id'), table_name='parties_version')

    # ### end Alembic commands ###

