"""empty message

Revision ID: e9e05a998ea9
Revises: 
Create Date: 2023-05-30 23:40:00.502108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9e05a998ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colin_last_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corp_types',
    sa.Column('corp_type_cd', sa.String(length=5), nullable=False),
    sa.Column('colin_ind', sa.String(length=1), nullable=False),
    sa.Column('corp_class', sa.String(length=10), nullable=False),
    sa.Column('short_desc', sa.String(length=25), nullable=False),
    sa.Column('full_desc', sa.String(length=100), nullable=False),
    sa.Column('legislation', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('corp_type_cd'),
    sqlite_autoincrement=True
    )
    op.create_table('corp_types_history',
    sa.Column('corp_type_cd', sa.String(length=5), autoincrement=False, nullable=False),
    sa.Column('colin_ind', sa.String(length=1), autoincrement=False, nullable=False),
    sa.Column('corp_class', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('short_desc', sa.String(length=25), autoincrement=False, nullable=False),
    sa.Column('full_desc', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('legislation', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('corp_type_cd', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('dc_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.Enum('business', 'business_relationship', name='credentialtype'), nullable=False),
    sa.Column('schema_id', sa.String(length=100), nullable=True),
    sa.Column('schema_name', sa.String(length=50), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=True),
    sa.Column('credential_definition_id', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('naics_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naics_key', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hierarchical_structure', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('class_title', sa.String(length=150), nullable=False),
    sa.Column('superscript', sa.String(length=5), nullable=True),
    sa.Column('class_definition', sa.String(length=5100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('naics_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_naics_structures_class_definition'), ['class_definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_structures_class_title'), ['class_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_structures_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_structures_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_structures_version'), ['version'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_structures_year'), ['year'], unique=False)

    op.create_table('office_types',
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('registration_bootstrap',
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    with op.batch_alter_table('registration_bootstrap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_bootstrap_account'), ['account'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('middlename', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('sub', sa.String(length=1024), nullable=True),
    sa.Column('iss', sa.String(length=1024), nullable=True),
    sa.Column('idp_userid', sa.String(length=1024), nullable=True),
    sa.Column('login_source', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_idp_userid'), ['idp_userid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('users_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('middlename', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('sub', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('iss', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('idp_userid', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('login_source', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_history_idp_userid'), ['idp_userid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_history_username'), ['username'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ledger_id', sa.Integer(), nullable=True),
    sa.Column('last_remote_ledger_id', sa.Integer(), nullable=True),
    sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ar_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_agm_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_coa_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_cod_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_name', sa.String(length=1000), nullable=True),
    sa.Column('legal_type', sa.String(length=10), nullable=True),
    sa.Column('founding_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restoration_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cco_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('continuation_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('tax_id', sa.String(length=15), nullable=True),
    sa.Column('fiscal_year_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restriction_ind', sa.Boolean(), nullable=True),
    sa.Column('last_ar_year', sa.Integer(), nullable=True),
    sa.Column('last_ar_reminder_year', sa.Integer(), nullable=True),
    sa.Column('association_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'HISTORICAL', 'LIQUIDATION', name='state'), nullable=True),
    sa.Column('state_filing_id', sa.Integer(), nullable=True),
    sa.Column('admin_freeze', sa.Boolean(), nullable=True),
    sa.Column('submitter_userid', sa.Integer(), nullable=True),
    sa.Column('send_ar_ind', sa.Boolean(), nullable=True),
    sa.Column('naics_key', sa.String(length=50), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('naics_description', sa.String(length=150), nullable=True),
    sa.Column('foreign_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True),
    sa.Column('foreign_identifier', sa.String(length=15), nullable=True),
    sa.Column('foreign_legal_name', sa.String(length=1000), nullable=True),
    sa.Column('foreign_legal_type', sa.String(length=10), nullable=True),
    sa.Column('foreign_incorporation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitter_userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_legal_name'), ['legal_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_tax_id'), ['tax_id'], unique=False)

    op.create_table('businesses_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_ledger_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_remote_ledger_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_ar_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_agm_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_coa_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_cod_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('legal_type', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('founding_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restoration_expiry_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dissolution_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cco_expiry_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('continuation_out_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('fiscal_year_end_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restriction_ind', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('last_ar_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_ar_reminder_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('association_type', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'HISTORICAL', 'LIQUIDATION', name='state'), autoincrement=False, nullable=True),
    sa.Column('state_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('admin_freeze', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('submitter_userid', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('send_ar_ind', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('naics_key', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('naics_code', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('naics_description', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('foreign_jurisdiction', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_identifier', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('foreign_legal_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('foreign_legal_type', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_incorporation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('businesses_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_history_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_history_legal_name'), ['legal_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_history_tax_id'), ['tax_id'], unique=False)

    op.create_table('naics_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('class_title', sa.String(length=150), nullable=False),
    sa.Column('element_type', sa.Enum('ALL_EXAMPLES', 'ILLUSTRATIVE_EXAMPLES', 'INCLUSIONS', 'EXCLUSIONS', name='elementtype'), nullable=False),
    sa.Column('element_description', sa.String(length=500), nullable=False),
    sa.Column('naics_structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['naics_structure_id'], ['naics_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('naics_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_naics_elements_class_title'), ['class_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_element_description'), ['element_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_element_type'), ['element_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_naics_structure_id'), ['naics_structure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_version'), ['version'], unique=False)
        batch_op.create_index(batch_op.f('ix_naics_elements_year'), ['year'], unique=False)

    op.create_table('dc_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.String(length=100), nullable=True),
    sa.Column('invitation_url', sa.String(length=4096), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connection_state', sa.String(length=50), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_type', sa.String(length=30), nullable=True),
    sa.Column('filing_sub_type', sa.String(length=30), nullable=True),
    sa.Column('filing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_status_code', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=4096), nullable=True),
    sa.Column('payment_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('paper_only', sa.Boolean(), nullable=True),
    sa.Column('colin_only', sa.Boolean(), nullable=True),
    sa.Column('payment_account', sa.String(length=30), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitter_roles', sa.String(length=200), nullable=True),
    sa.Column('tech_correction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('court_order_file_number', sa.String(length=20), nullable=True),
    sa.Column('court_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('court_order_effect_of_order', sa.String(length=500), nullable=True),
    sa.Column('order_details', sa.String(length=2000), nullable=True),
    sa.Column('deletion_locked', sa.Boolean(), nullable=True),
    sa.Column('approval_type', sa.String(length=15), nullable=True),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('temp_reg', sa.String(length=10), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('parent_filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['parent_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temp_reg'], ['registration_bootstrap.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_aliases_change_filing_id'), ['change_filing_id'], unique=False)

    op.create_table('aliases_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.String(length=1000), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('aliases_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_history_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_aliases_history_change_filing_id'), ['change_filing_id'], unique=False)

    op.create_table('colin_event_ids',
    sa.Column('colin_event_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('colin_event_id'),
    sa.UniqueConstraint('colin_event_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_filing_id'), ['filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_staff_id'), ['staff_id'], unique=False)

    op.create_table('dc_issued_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dc_definition_id', sa.Integer(), nullable=True),
    sa.Column('dc_connection_id', sa.Integer(), nullable=True),
    sa.Column('credential_exchange_id', sa.String(length=100), nullable=True),
    sa.Column('credential_id', sa.String(length=100), nullable=True),
    sa.Column('is_issued', sa.Boolean(), nullable=True),
    sa.Column('date_of_issue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dc_connection_id'], ['dc_connections.id'], ),
    sa.ForeignKeyConstraint(['dc_definition_id'], ['dc_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('file_key', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_filing_id'), ['filing_id'], unique=False)

    op.create_table('documents_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=30), autoincrement=False, nullable=False),
    sa.Column('file_key', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('documents_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_history_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_history_filing_id'), ['filing_id'], unique=False)

    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_type', sa.String(length=75), nullable=True),
    sa.Column('deactivated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['office_type'], ['office_types.identifier'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offices_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offices_change_filing_id'), ['change_filing_id'], unique=False)

    op.create_table('offices_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('office_type', sa.String(length=75), autoincrement=False, nullable=True),
    sa.Column('deactivated_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['office_type'], ['office_types.identifier'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('offices_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offices_history_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offices_history_change_filing_id'), ['change_filing_id'], unique=False)

    op.create_table('request_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('INFORM_CRA', 'GET_BN', 'CHANGE_DELIVERY_ADDRESS', 'CHANGE_MAILING_ADDRESS', 'CHANGE_NAME', 'CHANGE_STATUS', 'CHANGE_PARTY', name='requesttype'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('request_object', sa.Text(), nullable=True),
    sa.Column('response_object', sa.Text(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Enum('BN_HUB', name='servicename'), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.String(length=60), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_tracker_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_tracker_filing_id'), ['filing_id'], unique=False)

    op.create_table('share_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), nullable=True),
    sa.Column('max_shares', sa.Integer(), nullable=True),
    sa.Column('par_value_flag', sa.Boolean(), nullable=True),
    sa.Column('par_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('share_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_classes_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_classes_name'), ['name'], unique=False)

    op.create_table('share_classes_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('par_value_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('par_value', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('share_classes_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_classes_history_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_classes_history_name'), ['name'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=4096), nullable=True),
    sa.Column('street', sa.String(length=4096), nullable=True),
    sa.Column('street_additional', sa.String(length=4096), nullable=True),
    sa.Column('city', sa.String(length=4096), nullable=True),
    sa.Column('region', sa.String(length=4096), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=15), nullable=True),
    sa.Column('delivery_instructions', sa.String(length=4096), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_address_type'), ['address_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_street'), ['street'], unique=False)

    op.create_table('addresses_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('address_type', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('street', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('street_additional', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('city', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('region', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('country', sa.String(length=2), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('delivery_instructions', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('office_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('addresses_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_history_address_type'), ['address_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_history_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_history_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_history_street'), ['street'], unique=False)

    op.create_table('share_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), nullable=True),
    sa.Column('max_shares', sa.Integer(), nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('share_class_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['share_class_id'], ['share_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('share_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_series_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_series_name'), ['name'], unique=False)

    op.create_table('share_series_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('share_class_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['share_class_id'], ['share_classes.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('share_series_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_series_history_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_series_history_name'), ['name'], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('middle_initial', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_middle_initial'), ['middle_initial'], unique=False)

    op.create_table('parties_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('party_type', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=254), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('parties_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_history_change_filing_id'), ['change_filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_history_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_history_middle_initial'), ['middle_initial'], unique=False)

    op.create_table('party_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('party_roles_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('party_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sub_type', sa.String(length=20), nullable=True),
    sa.Column('signing_party_id', sa.Integer(), nullable=True),
    sa.Column('signing_date', sa.Date(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('change_filing_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['signing_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolutions_change_filing_id'), ['change_filing_id'], unique=False)

    op.create_table('resolutions_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('resolution_date', sa.Date(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('sub_type', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('signing_party_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('signing_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('change_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['change_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['signing_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('resolutions_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolutions_history_change_filing_id'), ['change_filing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resolutions_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolutions_history_change_filing_id'))

    op.drop_table('resolutions_history')
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolutions_change_filing_id'))

    op.drop_table('resolutions')
    op.drop_table('party_roles_history')
    op.drop_table('party_roles')
    with op.batch_alter_table('parties_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_history_middle_initial'))
        batch_op.drop_index(batch_op.f('ix_parties_history_first_name'))
        batch_op.drop_index(batch_op.f('ix_parties_history_change_filing_id'))

    op.drop_table('parties_history')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_middle_initial'))
        batch_op.drop_index(batch_op.f('ix_parties_first_name'))
        batch_op.drop_index(batch_op.f('ix_parties_change_filing_id'))

    op.drop_table('parties')
    with op.batch_alter_table('share_series_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_series_history_name'))
        batch_op.drop_index(batch_op.f('ix_share_series_history_change_filing_id'))

    op.drop_table('share_series_history')
    with op.batch_alter_table('share_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_series_name'))
        batch_op.drop_index(batch_op.f('ix_share_series_change_filing_id'))

    op.drop_table('share_series')
    with op.batch_alter_table('addresses_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_history_street'))
        batch_op.drop_index(batch_op.f('ix_addresses_history_change_filing_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_history_business_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_history_address_type'))

    op.drop_table('addresses_history')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_street'))
        batch_op.drop_index(batch_op.f('ix_addresses_change_filing_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_business_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_address_type'))

    op.drop_table('addresses')
    with op.batch_alter_table('share_classes_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_classes_history_name'))
        batch_op.drop_index(batch_op.f('ix_share_classes_history_change_filing_id'))

    op.drop_table('share_classes_history')
    with op.batch_alter_table('share_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_classes_name'))
        batch_op.drop_index(batch_op.f('ix_share_classes_change_filing_id'))

    op.drop_table('share_classes')
    with op.batch_alter_table('request_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_tracker_filing_id'))
        batch_op.drop_index(batch_op.f('ix_request_tracker_business_id'))

    op.drop_table('request_tracker')
    with op.batch_alter_table('offices_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offices_history_change_filing_id'))
        batch_op.drop_index(batch_op.f('ix_offices_history_business_id'))

    op.drop_table('offices_history')
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offices_change_filing_id'))
        batch_op.drop_index(batch_op.f('ix_offices_business_id'))

    op.drop_table('offices')
    with op.batch_alter_table('documents_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_history_filing_id'))
        batch_op.drop_index(batch_op.f('ix_documents_history_business_id'))

    op.drop_table('documents_history')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_filing_id'))
        batch_op.drop_index(batch_op.f('ix_documents_business_id'))

    op.drop_table('documents')
    op.drop_table('dc_issued_credentials')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_staff_id'))
        batch_op.drop_index(batch_op.f('ix_comments_filing_id'))
        batch_op.drop_index(batch_op.f('ix_comments_business_id'))

    op.drop_table('comments')
    op.drop_table('colin_event_ids')
    with op.batch_alter_table('aliases_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_history_change_filing_id'))
        batch_op.drop_index(batch_op.f('ix_aliases_history_alias'))

    op.drop_table('aliases_history')
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_change_filing_id'))
        batch_op.drop_index(batch_op.f('ix_aliases_alias'))

    op.drop_table('aliases')
    op.drop_table('filings')
    op.drop_table('dc_connections')
    with op.batch_alter_table('naics_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_naics_elements_year'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_version'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_naics_structure_id'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_level'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_element_type'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_element_description'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_code'))
        batch_op.drop_index(batch_op.f('ix_naics_elements_class_title'))

    op.drop_table('naics_elements')
    with op.batch_alter_table('businesses_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_history_tax_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_history_legal_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_history_identifier'))

    op.drop_table('businesses_history')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_tax_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_legal_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_identifier'))

    op.drop_table('businesses')
    with op.batch_alter_table('users_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_history_username'))
        batch_op.drop_index(batch_op.f('ix_users_history_idp_userid'))

    op.drop_table('users_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_idp_userid'))

    op.drop_table('users')
    with op.batch_alter_table('registration_bootstrap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_bootstrap_account'))

    op.drop_table('registration_bootstrap')
    op.drop_table('office_types')
    with op.batch_alter_table('naics_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_naics_structures_year'))
        batch_op.drop_index(batch_op.f('ix_naics_structures_version'))
        batch_op.drop_index(batch_op.f('ix_naics_structures_level'))
        batch_op.drop_index(batch_op.f('ix_naics_structures_code'))
        batch_op.drop_index(batch_op.f('ix_naics_structures_class_title'))
        batch_op.drop_index(batch_op.f('ix_naics_structures_class_definition'))

    op.drop_table('naics_structures')
    op.drop_table('dc_definitions')
    op.drop_table('corp_types_history')
    op.drop_table('corp_types')
    op.drop_table('colin_last_update')
    # ### end Alembic commands ###
