"""digital-credentials

Revision ID: ecfeee53451a
Revises: 37acd517fe98
Create Date: 2022-09-02 16:55:09.061885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecfeee53451a'
down_revision = '37acd517fe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.Enum('business', 'business_relationship', name='credentialtype'), nullable=False),
    sa.Column('schema_id', sa.String(length=100), nullable=True),
    sa.Column('schema_name', sa.String(length=50), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=True),
    sa.Column('credential_definition_id', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dc_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.String(length=100), nullable=True),
    sa.Column('invitation_url', sa.String(length=4096), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connection_state', sa.String(length=50), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dc_issued_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dc_definition_id', sa.Integer(), nullable=True),
    sa.Column('dc_connection_id', sa.Integer(), nullable=True),
    sa.Column('credential_exchange_id', sa.String(length=100), nullable=True),
    sa.Column('credential_id', sa.String(length=100), nullable=True),
    sa.Column('is_issued', sa.Boolean(), nullable=True),
    sa.Column('date_of_issue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dc_connection_id'], ['dc_connections.id'], ),
    sa.ForeignKeyConstraint(['dc_definition_id'], ['dc_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dc_issued_credentials')
    op.drop_table('dc_connections')
    op.drop_table('dc_definitions')
    # ### end Alembic commands ###
