"""empty message

Revision ID: ee956cbf198a
Revises: a6e3fdc238dd
Create Date: 2022-08-17 16:41:13.184365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee956cbf198a'
down_revision = 'a6e3fdc238dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses_version', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'start_date')
    op.drop_column('businesses_version', 'start_date')
    # ### end Alembic commands ###
