"""add_meta_data_to_batch_processing

Revision ID: ef8f033d317b
Revises: 508c7466b2af
Create Date: 2024-05-16 16:24:16.922376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = 'ef8f033d317b'
down_revision = '508c7466b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_processing', sa.Column('meta_data', JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_processing', 'meta_data')
    # ### end Alembic commands ###
