"""empty message

Revision ID: f3fb008e7b83
Revises: 7575af513efb
Create Date: 2020-07-09 12:06:12.392138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3fb008e7b83'
down_revision = '7575af513efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases_version',
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('alias', sa.String(length=1000), autoincrement=False, nullable=False),
                    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
                    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    op.create_index(op.f('ix_aliases_version_end_transaction_id'), 'aliases_version', ['end_transaction_id'],
                    unique=False)
    op.create_index(op.f('ix_aliases_version_operation_type'), 'aliases_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_aliases_version_transaction_id'), 'aliases_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_aliases_version_alias'), 'aliases_version', ['alias'], unique=False)

    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliases_alias'), 'aliases', ['alias'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aliases_alias'), table_name='aliases')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_aliases_version_end_transaction_id'), table_name='aliases_version')
    op.drop_index(op.f('ix_aliases_version_operation_type'), table_name='aliases_version')
    op.drop_index(op.f('ix_aliases_version_transaction_id'), table_name='aliases_version')
    op.drop_index(op.f('ix_aliases_version_alias'), table_name='aliases_version')
    op.drop_table('aliases_version')
    # ### end Alembic commands ###
