"""add_configurations_table

Revision ID: f4f93ea8887e
Revises: 246e135484b3
Create Date: 2024-05-01 09:20:48.050322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f93ea8887e'
down_revision = '246e135484b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'configurations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('val', sa.String(length=100), nullable=False),
        sa.Column('short_description', sa.String(length=150), nullable=True),
        sa.Column('full_description', sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute("""insert into configurations (name, val, short_description, full_description) values
               ('NUM_DISSOLUTIONS_ALLOWED', '5', 'Number of involuntary dissolutions per day.', 'Number of involuntary dissolutions per day.'),
               ('MAX_DISSOLUTIONS_ALLOWED', '2000', 'Max number of involuntary dissolutions permitted per day.', 'Max number of involuntary dissolutions permitted per day.  This is used to validate the upper limit for NUM_DISSOLUTIONS_ALLOWED.'),
               ('NEW_DISSOLUTIONS_SCHEDULE', '0 0 * * *', 'Cron string for which days new involuntary dissolutions can be initiated.', 'Cron string for which days new involuntary dissolutions can be initiated.'),
               ('DISSOLUTIONS_ON_HOLD', 'False', 'Flag to put all dissolution processes on hold.', 'Flag to put all dissolution processes on hold.')
               """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    # ### end Alembic commands ###
