"""add_foreign_jurisdiction_region_amalgamating_business

Revision ID: f978e34aa8bb
Revises: 5238dd8fb805
Create Date: 2024-01-08 12:43:33.140159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f978e34aa8bb'
down_revision = '5238dd8fb805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amalgamating_business', sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amalgamating_business', 'foreign_jurisdiction_region')
    # ### end Alembic commands ###
