"""empty message

Revision ID: fa0f38366a1d
Revises: 5652df7736b8
Create Date: 2019-04-23 15:31:25.510887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa0f38366a1d'
down_revision = '5652df7736b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business', sa.Column('last_remote_ledger_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('business', 'last_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('business', 'last_remote_ledger_timestamp')
    op.drop_column('business', 'last_ledger_timestamp')
    # ### end Alembic commands ###
