-- Minimal preserved-table schema for delta restore harness smoke tests.
-- This is intentionally smaller than colin_corps_extract_postgres_ddl but keeps
-- the columns referenced by delta table_config, classification, and apply SQL.

DROP TABLE IF EXISTS auth_component_operation CASCADE;
DROP TABLE IF EXISTS auth_processing CASCADE;
DROP TABLE IF EXISTS colin_tracking CASCADE;
DROP TABLE IF EXISTS corp_processing CASCADE;
DROP TABLE IF EXISTS mig_corp_account CASCADE;
DROP TABLE IF EXISTS mig_corp_batch CASCADE;
DROP TABLE IF EXISTS mig_batch CASCADE;
DROP TABLE IF EXISTS mig_group CASCADE;
DROP TABLE IF EXISTS bar_corps CASCADE;
DROP TABLE IF EXISTS corps_with_third_party CASCADE;
DROP TABLE IF EXISTS exclude_corps CASCADE;
DROP TABLE IF EXISTS excluded_email_domain_patterns CASCADE;
DROP TABLE IF EXISTS excluded_email_domains CASCADE;
DROP TABLE IF EXISTS excluded_emails CASCADE;
DROP TABLE IF EXISTS bad_emails CASCADE;
DROP TABLE IF EXISTS email_domain_groups CASCADE;
DROP TABLE IF EXISTS demigrated_filings CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS corporation CASCADE;

CREATE TABLE corporation (
  corp_num text PRIMARY KEY
);

CREATE TABLE event (
  event_id bigint PRIMARY KEY
);

CREATE TABLE email_domain_groups (
  email_domain text PRIMARY KEY,
  group_name text
);

CREATE TABLE bad_emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE,
  notes text
);

CREATE TABLE excluded_emails (
  email text PRIMARY KEY,
  notes text
);

CREATE TABLE excluded_email_domains (
  email_domain text PRIMARY KEY,
  notes text
);

CREATE TABLE excluded_email_domain_patterns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_domain text NOT NULL,
  local_part_pattern text NOT NULL,
  notes text,
  UNIQUE (email_domain, local_part_pattern)
);

CREATE TABLE exclude_corps (
  corp_num text PRIMARY KEY,
  notes text
);

CREATE TABLE corps_with_third_party (
  corp_num text,
  vendor text,
  vendor_count integer,
  notes text
);

CREATE TABLE bar_corps (
  identifier text,
  notes text
);

CREATE TABLE mig_group (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  target_environment text,
  source_db text
);

CREATE TABLE mig_batch (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mig_group_id bigint,
  name text,
  target_environment text
);

CREATE TABLE mig_corp_batch (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mig_batch_id bigint,
  corp_num text
);

CREATE TABLE mig_corp_account (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  corp_num text,
  target_environment text,
  account_id text,
  mig_batch_id bigint
);

CREATE TABLE corp_processing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  corp_num text,
  flow_name text,
  environment text,
  mig_batch_id bigint,
  last_processed_event_id bigint,
  failed_event_id bigint,
  processed_status text,
  last_error text,
  last_modified timestamptz
);

CREATE TABLE colin_tracking (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  corp_num text,
  flow_name text,
  environment text,
  mig_batch_id bigint,
  processed_status text,
  last_modified timestamptz
);

CREATE TABLE auth_processing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  corp_num text,
  flow_name text,
  environment text,
  operation text,
  operation_scope text,
  attempt_key text,
  mig_batch_id bigint,
  processed_status text,
  last_modified timestamptz
);

CREATE TABLE auth_component_operation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_processing_id bigint,
  component_name text,
  operation text,
  status text,
  payload text
);

CREATE TABLE demigrated_filings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filing_id integer UNIQUE,
  corp_num text,
  filing_date timestamptz,
  filing_type text,
  filing_json jsonb,
  payment_id integer,
  transaction_id integer,
  business_id integer,
  submitter_id integer,
  status text,
  payment_completion_date timestamptz,
  paper_only boolean,
  completion_date timestamptz,
  effective_date timestamptz,
  source text,
  parent_filing_id integer,
  payment_status_code text,
  temp_reg text,
  payment_account text,
  court_order_file_number text,
  court_order_date timestamptz,
  court_order_effect_of_order text,
  tech_correction_json jsonb,
  colin_only boolean,
  deletion_locked boolean,
  order_details text,
  submitter_roles text,
  meta_data jsonb,
  filing_sub_type text,
  approval_type text,
  application_date timestamptz,
  notice_date timestamptz,
  resubmission_date timestamptz,
  hide_in_ledger boolean NOT NULL DEFAULT false,
  withdrawn_filing_id integer,
  withdrawal_pending boolean NOT NULL DEFAULT false,
  lear_only boolean,
  notes text
);
