"""empty message

Revision ID: 786dac4b44ef
Revises:
Create Date: 2021-06-23 12:47:22.358546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '786dac4b44ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_processing',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source', sa.String(length=36), nullable=True),
                    sa.Column('message_id', sa.String(length=60), nullable=False),
                    sa.Column('identifier', sa.String(length=36), nullable=True),
                    sa.Column('message_type', sa.String(length=35), nullable=False),
                    sa.Column('status', sa.String(length=10), nullable=False),
                    sa.Column('message_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('message_seen_count', sa.Integer(), nullable=False),
                    sa.Column('last_error', sa.String(length=1000), nullable=True),
                    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_processing_identifier'), 'message_processing', ['identifier'], unique=False)
    op.create_index(op.f('ix_message_processing_message_id'), 'message_processing', ['message_id'], unique=True)
    op.create_index(op.f('ix_message_processing_message_type'), 'message_processing', ['message_type'], unique=False)
    op.create_index(op.f('ix_message_processing_status'), 'message_processing', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_processing_source'), table_name='message_processing')
    op.drop_index(op.f('ix_message_processing_status'), table_name='message_processing')
    op.drop_index(op.f('ix_message_processing_message_type'), table_name='message_processing')
    op.drop_index(op.f('ix_message_processing_message_id'), table_name='message_processing')
    op.drop_index(op.f('ix_message_processing_identifier'), table_name='message_processing')
    op.drop_table('message_processing')
    # ### end Alembic commands ###


