---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "update-colin-filings"
  annotations:
    description: "Scheduled task to update colin-api with completed filings from legal-api"
    tags: "cronjob"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "update-colin-filings"
  spec:
    concurrencyPolicy: "Forbid"
    schedule: "0 * * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: "Never"
            containers:
            - name: "update-colin-filings"
              image: "docker-registry.default.svc:5000/gl2uos-tools/update-colin-filings:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                - name: COLIN_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ROUTE
                      name: colin-api-${ENV_TAG}-config
                - name: SENTRY_DSN
                  valueFrom:
                    configMapKeyRef:
                      key: SENTRY_DSN
                      name: updater-jobs-${ENV_TAG}-config
                - name: LEGAL_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ROUTE
                      name: legal-api-${ENV_TAG}-config
                - name: AUTH_URL
                  valueFrom:
                    configMapKeyRef:
                      key: AUTH_URL
                      name: updater-jobs-${ENV_TAG}-config
                - name: AUTH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_USERNAME
                      name: updater-job
                - name: AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_PASSWORD
                      name: updater-job
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "dev"
        },
]
