---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "update-colin-filings"
  annotations:
    description: "Scheduled task to update colin-api with completed filings from legal-api"
    tags: "cronjob"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "update-colin-filings"
  spec:
    schedule: "* */1 * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "update-colin-filings"
              image: "docker-registry.default.svc:5000/gl2uos-tools/update-colin-filings:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                - name: COLIN_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ROUTE
                      name: colin-api-dev-config
                - name: LEGAL_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ROUTE
                      name: legal-api-dev-config
            restartPolicy: "Never"
            concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "dev"
        },
]
