"""empty message

Revision ID: 3745bff11567
Revises: 
Create Date: 2025-03-22 23:15:49.039060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from business_model.models.custom_db_types import PostgreSQLXML
# revision identifiers, used by Alembic.
revision = '1a45bff11567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('address_type', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('street', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('street_additional', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('city', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('region', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('country', sa.String(length=2), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('delivery_instructions', sa.String(length=4096), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('furnishings_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('office_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_addresses_version_address_type'), 'addresses_version', ['address_type'], unique=False)
    op.create_index(op.f('ix_addresses_version_business_id'), 'addresses_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_addresses_version_end_transaction_id'), 'addresses_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_addresses_version_operation_type'), 'addresses_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_addresses_version_street'), 'addresses_version', ['street'], unique=False)
    op.create_index(op.f('ix_addresses_version_transaction_id'), 'addresses_version', ['transaction_id'], unique=False)
    op.create_table('aliases_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.String(length=1000), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_aliases_version_alias'), 'aliases_version', ['alias'], unique=False)
    op.create_index(op.f('ix_aliases_version_end_transaction_id'), 'aliases_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_aliases_version_operation_type'), 'aliases_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_aliases_version_transaction_id'), 'aliases_version', ['transaction_id'], unique=False)
    op.create_table('amalgamating_businesses_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.Enum('amalgamating', 'holding', 'primary', name='role'), autoincrement=False, nullable=False),
    sa.Column('foreign_jurisdiction', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('foreign_identifier', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('amalgamation_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_amalgamating_businesses_version_business_id'), 'amalgamating_businesses_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_end_transaction_id'), 'amalgamating_businesses_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_operation_type'), 'amalgamating_businesses_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_amalgamating_businesses_version_transaction_id'), 'amalgamating_businesses_version', ['transaction_id'], unique=False)
    op.create_table('amalgamations_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('amalgamation_type', sa.Enum('regular', 'vertical', 'horizontal', 'unknown', name='amalgamationtypes'), autoincrement=False, nullable=False),
    sa.Column('amalgamation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('court_approval', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('filing_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_amalgamations_version_business_id'), 'amalgamations_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_end_transaction_id'), 'amalgamations_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_operation_type'), 'amalgamations_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_amalgamations_version_transaction_id'), 'amalgamations_version', ['transaction_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.Enum('INVOLUNTARY_DISSOLUTION', name='batchtype'), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'ERROR', name='batchstatus'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_ledger_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_remote_ledger_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_ar_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_agm_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_coa_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_cod_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('legal_type', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('founding_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restoration_expiry_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dissolution_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('continuation_out_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('amalgamation_out_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('fiscal_year_end_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restriction_ind', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('last_ar_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_ar_reminder_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_tr_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('association_type', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'HISTORICAL', 'LIQUIDATION', name='state'), autoincrement=False, nullable=True),
    sa.Column('state_filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('admin_freeze', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('submitter_userid', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('send_ar_ind', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('no_dissolution', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('naics_key', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('naics_code', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('naics_description', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('foreign_jurisdiction', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('foreign_legal_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_businesses_version_end_transaction_id'), 'businesses_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_businesses_version_identifier'), 'businesses_version', ['identifier'], unique=False)
    op.create_index(op.f('ix_businesses_version_legal_name'), 'businesses_version', ['legal_name'], unique=False)
    op.create_index(op.f('ix_businesses_version_operation_type'), 'businesses_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_businesses_version_tax_id'), 'businesses_version', ['tax_id'], unique=False)
    op.create_index(op.f('ix_businesses_version_transaction_id'), 'businesses_version', ['transaction_id'], unique=False)
    op.create_table('colin_last_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('NUM_DISSOLUTIONS_ALLOWED', 'MAX_DISSOLUTIONS_ALLOWED', 'DISSOLUTIONS_STAGE_1_SCHEDULE', 'DISSOLUTIONS_STAGE_2_SCHEDULE', 'DISSOLUTIONS_STAGE_3_SCHEDULE', name='names'), nullable=False),
    sa.Column('val', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=150), nullable=True),
    sa.Column('full_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corp_types',
    sa.Column('corp_type_cd', sa.String(length=5), nullable=False),
    sa.Column('colin_ind', sa.String(length=1), nullable=False),
    sa.Column('corp_class', sa.String(length=10), nullable=False),
    sa.Column('short_desc', sa.String(length=25), nullable=False),
    sa.Column('full_desc', sa.String(length=100), nullable=False),
    sa.Column('legislation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('corp_type_cd')
    )
    op.create_table('dc_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.Enum('business', 'business_relationship', name='credentialtype'), nullable=False),
    sa.Column('schema_id', sa.String(length=100), nullable=True),
    sa.Column('schema_name', sa.String(length=50), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=True),
    sa.Column('credential_definition_id', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=30), autoincrement=False, nullable=False),
    sa.Column('file_key', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_documents_version_business_id'), 'documents_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_documents_version_end_transaction_id'), 'documents_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_documents_version_filing_id'), 'documents_version', ['filing_id'], unique=False)
    op.create_index(op.f('ix_documents_version_operation_type'), 'documents_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_documents_version_transaction_id'), 'documents_version', ['transaction_id'], unique=False)
    op.create_table('jurisdictions_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('country', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('region', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('incorporation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expro_identifier', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('expro_legal_name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('filing_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_jurisdictions_version_business_id'), 'jurisdictions_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_jurisdictions_version_end_transaction_id'), 'jurisdictions_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_jurisdictions_version_filing_id'), 'jurisdictions_version', ['filing_id'], unique=False)
    op.create_index(op.f('ix_jurisdictions_version_operation_type'), 'jurisdictions_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_jurisdictions_version_transaction_id'), 'jurisdictions_version', ['transaction_id'], unique=False)
    op.create_table('naics_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naics_key', postgresql.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hierarchical_structure', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('class_title', sa.String(length=150), nullable=False),
    sa.Column('superscript', sa.String(length=5), nullable=True),
    sa.Column('class_definition', sa.String(length=5100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naics_structures_class_definition'), 'naics_structures', ['class_definition'], unique=False)
    op.create_index(op.f('ix_naics_structures_class_title'), 'naics_structures', ['class_title'], unique=False)
    op.create_index(op.f('ix_naics_structures_code'), 'naics_structures', ['code'], unique=False)
    op.create_index(op.f('ix_naics_structures_level'), 'naics_structures', ['level'], unique=False)
    op.create_index(op.f('ix_naics_structures_version'), 'naics_structures', ['version'], unique=False)
    op.create_index(op.f('ix_naics_structures_year'), 'naics_structures', ['year'], unique=False)
    op.create_table('office_types',
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('offices_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('office_type', sa.String(length=75), autoincrement=False, nullable=True),
    sa.Column('deactivated_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_offices_version_business_id'), 'offices_version', ['business_id'], unique=False)
    op.create_index(op.f('ix_offices_version_end_transaction_id'), 'offices_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_offices_version_operation_type'), 'offices_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_offices_version_transaction_id'), 'offices_version', ['transaction_id'], unique=False)
    op.create_table('parties_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('party_type', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=254), autoincrement=False, nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_parties_version_end_transaction_id'), 'parties_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_parties_version_first_name'), 'parties_version', ['first_name'], unique=False)
    op.create_index(op.f('ix_parties_version_middle_initial'), 'parties_version', ['middle_initial'], unique=False)
    op.create_index(op.f('ix_parties_version_operation_type'), 'parties_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_parties_version_transaction_id'), 'parties_version', ['transaction_id'], unique=False)
    op.create_table('party_roles_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('filing_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('party_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_party_roles_version_end_transaction_id'), 'party_roles_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_party_roles_version_operation_type'), 'party_roles_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_party_roles_version_transaction_id'), 'party_roles_version', ['transaction_id'], unique=False)
    op.create_table('registration_bootstrap',
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_index(op.f('ix_registration_bootstrap_account'), 'registration_bootstrap', ['account'], unique=False)
    op.create_table('resolutions_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('resolution_date', sa.Date(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('sub_type', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('signing_party_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('signing_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_resolutions_version_end_transaction_id'), 'resolutions_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_resolutions_version_operation_type'), 'resolutions_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_resolutions_version_transaction_id'), 'resolutions_version', ['transaction_id'], unique=False)
    op.create_table('share_classes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Numeric(precision=20), autoincrement=False, nullable=True),
    sa.Column('par_value_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('par_value', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('currency_additional', sa.String(length=40), autoincrement=False, nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_share_classes_version_end_transaction_id'), 'share_classes_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_share_classes_version_name'), 'share_classes_version', ['name'], unique=False)
    op.create_index(op.f('ix_share_classes_version_operation_type'), 'share_classes_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_share_classes_version_transaction_id'), 'share_classes_version', ['transaction_id'], unique=False)
    op.create_table('share_series_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('max_shares', sa.Numeric(precision=20), autoincrement=False, nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('share_class_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_share_series_version_end_transaction_id'), 'share_series_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_share_series_version_name'), 'share_series_version', ['name'], unique=False)
    op.create_index(op.f('ix_share_series_version_operation_type'), 'share_series_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_share_series_version_transaction_id'), 'share_series_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('middlename', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('sub', sa.String(length=36), nullable=True),
    sa.Column('iss', sa.String(length=1024), nullable=True),
    sa.Column('idp_userid', sa.String(length=256), nullable=True),
    sa.Column('login_source', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    op.create_index(op.f('ix_users_idp_userid'), 'users', ['idp_userid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('users_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('middlename', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('sub', sa.String(length=36), autoincrement=False, nullable=True),
    sa.Column('iss', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('idp_userid', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('login_source', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_users_version_end_transaction_id'), 'users_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_users_version_idp_userid'), 'users_version', ['idp_userid'], unique=False)
    op.create_index(op.f('ix_users_version_operation_type'), 'users_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_users_version_transaction_id'), 'users_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_users_version_username'), 'users_version', ['username'], unique=False)
    op.create_table('xml_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', PostgreSQLXML(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True, onupdate=sa.func.now()),
    sa.Column('last_ledger_id', sa.Integer(), nullable=True),
    sa.Column('last_remote_ledger_id', sa.Integer(), nullable=True),
    sa.Column('last_ledger_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ar_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_agm_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_coa_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_cod_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_name', sa.String(length=1000), nullable=True),
    sa.Column('legal_type', sa.String(length=10), nullable=True),
    sa.Column('founding_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restoration_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('continuation_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amalgamation_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('tax_id', sa.String(length=15), nullable=True),
    sa.Column('fiscal_year_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restriction_ind', sa.Boolean(), nullable=True),
    sa.Column('last_ar_year', sa.Integer(), nullable=True),
    sa.Column('last_ar_reminder_year', sa.Integer(), nullable=True),
    sa.Column('last_tr_year', sa.Integer(), nullable=True),
    sa.Column('association_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'HISTORICAL', 'LIQUIDATION', name='state'), nullable=True),
    sa.Column('state_filing_id', sa.Integer(), nullable=True),
    sa.Column('admin_freeze', sa.Boolean(), nullable=True),
    sa.Column('submitter_userid', sa.Integer(), nullable=True),
    sa.Column('send_ar_ind', sa.Boolean(), nullable=True),
    sa.Column('no_dissolution', sa.Boolean(), nullable=True),
    sa.Column('naics_key', sa.String(length=50), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('naics_description', sa.String(length=150), nullable=True),
    sa.Column('foreign_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True),
    sa.Column('foreign_legal_name', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['submitter_userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_identifier'), 'businesses', ['identifier'], unique=False)
    op.create_index(op.f('ix_businesses_legal_name'), 'businesses', ['legal_name'], unique=False)
    op.create_index(op.f('ix_businesses_tax_id'), 'businesses', ['tax_id'], unique=False)
    op.create_table('furnishing_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xml_payload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['xml_payload_id'], ['xml_payloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furnishing_groups_xml_payload_id'), 'furnishing_groups', ['xml_payload_id'], unique=False)
    op.create_table('naics_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('class_title', sa.String(length=150), nullable=False),
    sa.Column('element_type', sa.Enum('ALL_EXAMPLES', 'ILLUSTRATIVE_EXAMPLES', 'INCLUSIONS', 'EXCLUSIONS', name='elementtype'), nullable=False),
    sa.Column('element_description', sa.String(length=500), nullable=False),
    sa.Column('naics_structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['naics_structure_id'], ['naics_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naics_elements_class_title'), 'naics_elements', ['class_title'], unique=False)
    op.create_index(op.f('ix_naics_elements_code'), 'naics_elements', ['code'], unique=False)
    op.create_index(op.f('ix_naics_elements_element_description'), 'naics_elements', ['element_description'], unique=False)
    op.create_index(op.f('ix_naics_elements_element_type'), 'naics_elements', ['element_type'], unique=False)
    op.create_index(op.f('ix_naics_elements_level'), 'naics_elements', ['level'], unique=False)
    op.create_index(op.f('ix_naics_elements_naics_structure_id'), 'naics_elements', ['naics_structure_id'], unique=False)
    op.create_index(op.f('ix_naics_elements_version'), 'naics_elements', ['version'], unique=False)
    op.create_index(op.f('ix_naics_elements_year'), 'naics_elements', ['year'], unique=False)
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliases_alias'), 'aliases', ['alias'], unique=False)
    op.create_table('dc_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.String(length=100), nullable=True),
    sa.Column('invitation_url', sa.String(length=4096), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connection_state', sa.String(length=50), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dc_issued_business_user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_type', sa.String(length=30), nullable=True),
    sa.Column('filing_sub_type', sa.String(length=30), nullable=True),
    sa.Column('filing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_status_code', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=4096), nullable=True),
    sa.Column('payment_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('paper_only', sa.Boolean(), nullable=True),
    sa.Column('colin_only', sa.Boolean(), nullable=True),
    sa.Column('payment_account', sa.String(length=30), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitter_roles', sa.String(length=200), nullable=True),
    sa.Column('tech_correction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('court_order_file_number', sa.String(length=20), nullable=True),
    sa.Column('court_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('court_order_effect_of_order', sa.String(length=500), nullable=True),
    sa.Column('order_details', sa.String(length=2000), nullable=True),
    sa.Column('deletion_locked', sa.Boolean(), nullable=True),
    sa.Column('approval_type', sa.String(length=15), nullable=True),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resubmission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hide_in_ledger', sa.Boolean(), nullable=True),
    sa.Column('withdrawal_pending', sa.Boolean(), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('temp_reg', sa.String(length=10), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('parent_filing_id', sa.Integer(), nullable=True),
    sa.Column('withdrawn_filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['parent_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temp_reg'], ['registration_bootstrap.identifier'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['withdrawn_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furnishings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('furnishing_type', sa.Enum('EMAIL', 'MAIL', 'GAZETTE', name='furnishingtype'), nullable=False),
    sa.Column('furnishing_name', sa.Enum('DISSOLUTION_COMMENCEMENT_NO_AR', 'DISSOLUTION_COMMENCEMENT_NO_TR', 'DISSOLUTION_COMMENCEMENT_NO_AR_XPRO', 'DISSOLUTION_COMMENCEMENT_NO_TR_XPRO', 'INTENT_TO_DISSOLVE', 'INTENT_TO_DISSOLVE_XPRO', 'CORP_DISSOLVED', 'CORP_DISSOLVED_XPRO', name='furnishingname'), nullable=False),
    sa.Column('business_identifier', sa.String(length=10), nullable=False),
    sa.Column('processed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSED', 'FAILED', name='furnishingstatus'), nullable=False),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('last_ar_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_name', sa.String(length=1000), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('furnishing_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['furnishing_group_id'], ['furnishing_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furnishings_batch_id'), 'furnishings', ['batch_id'], unique=False)
    op.create_index(op.f('ix_furnishings_business_id'), 'furnishings', ['business_id'], unique=False)
    op.create_index(op.f('ix_furnishings_furnishing_group_id'), 'furnishings', ['furnishing_group_id'], unique=False)
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_type', sa.String(length=75), nullable=True),
    sa.Column('deactivated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['office_type'], ['office_types.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_business_id'), 'offices', ['business_id'], unique=False)
    op.create_table('share_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), nullable=True),
    sa.Column('max_shares', sa.Numeric(precision=20), nullable=True),
    sa.Column('par_value_flag', sa.Boolean(), nullable=True),
    sa.Column('par_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('currency_additional', sa.String(length=40), nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_classes_name'), 'share_classes', ['name'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=4096), nullable=True),
    sa.Column('street', sa.String(length=4096), nullable=True),
    sa.Column('street_additional', sa.String(length=4096), nullable=True),
    sa.Column('city', sa.String(length=4096), nullable=True),
    sa.Column('region', sa.String(length=4096), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=15), nullable=True),
    sa.Column('delivery_instructions', sa.String(length=4096), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('furnishings_id', sa.Integer(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['furnishings_id'], ['furnishings.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_address_type'), 'addresses', ['address_type'], unique=False)
    op.create_index(op.f('ix_addresses_business_id'), 'addresses', ['business_id'], unique=False)
    op.create_index(op.f('ix_addresses_street'), 'addresses', ['street'], unique=False)
    op.create_table('amalgamations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amalgamation_type', sa.Enum('regular', 'vertical', 'horizontal', 'unknown', name='amalgamationtypes'), nullable=False),
    sa.Column('amalgamation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('court_approval', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amalgamations_business_id'), 'amalgamations', ['business_id'], unique=False)
    op.create_table('batch_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_identifier', sa.String(length=10), nullable=False),
    sa.Column('step', sa.Enum('WARNING_LEVEL_1', 'WARNING_LEVEL_2', 'DISSOLUTION', name='batchprocessingstep'), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PROCESSING', 'QUEUED', 'WITHDRAWN', 'COMPLETED', 'ERROR', name='batchprocessingstatus'), nullable=False),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_processing_batch_id'), 'batch_processing', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_processing_business_id'), 'batch_processing', ['business_id'], unique=False)
    op.create_index(op.f('ix_batch_processing_filing_id'), 'batch_processing', ['filing_id'], unique=False)
    op.create_table('colin_event_ids',
    sa.Column('colin_event_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('colin_event_id'),
    sa.UniqueConstraint('colin_event_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_business_id'), 'comments', ['business_id'], unique=False)
    op.create_index(op.f('ix_comments_filing_id'), 'comments', ['filing_id'], unique=False)
    op.create_index(op.f('ix_comments_staff_id'), 'comments', ['staff_id'], unique=False)
    op.create_table('consent_continuation_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('continuation_out', 'amalgamation_out', name='consenttypes'), nullable=False),
    sa.Column('foreign_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('dc_issued_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dc_definition_id', sa.Integer(), nullable=True),
    sa.Column('dc_connection_id', sa.Integer(), nullable=True),
    sa.Column('credential_exchange_id', sa.String(length=100), nullable=True),
    sa.Column('credential_id', sa.String(length=10), nullable=True),
    sa.Column('is_issued', sa.Boolean(), nullable=True),
    sa.Column('date_of_issue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('credential_revocation_id', sa.String(length=10), nullable=True),
    sa.Column('revocation_registry_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['dc_connection_id'], ['dc_connections.id'], ),
    sa.ForeignKeyConstraint(['dc_definition_id'], ['dc_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('file_key', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=1000), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_business_id'), 'documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_documents_filing_id'), 'documents', ['filing_id'], unique=False)
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('legal_name', sa.String(length=1000), nullable=True),
    sa.Column('tax_id', sa.String(length=15), nullable=True),
    sa.Column('incorporation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expro_identifier', sa.String(length=10), nullable=True),
    sa.Column('expro_legal_name', sa.String(length=1000), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdictions_business_id'), 'jurisdictions', ['business_id'], unique=False)
    op.create_index(op.f('ix_jurisdictions_filing_id'), 'jurisdictions', ['filing_id'], unique=False)
    op.create_table('request_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('INFORM_CRA', 'GET_BN', 'CHANGE_DELIVERY_ADDRESS', 'CHANGE_MAILING_ADDRESS', 'CHANGE_NAME', 'CHANGE_STATUS', 'CHANGE_PARTY', name='requesttype'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('request_object', sa.Text(), nullable=True),
    sa.Column('response_object', sa.Text(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Enum('BN_HUB', name='servicename'), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.String(length=60), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_tracker_business_id'), 'request_tracker', ['business_id'], unique=False)
    op.create_index(op.f('ix_request_tracker_filing_id'), 'request_tracker', ['filing_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_number', sa.String(length=15), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_REVIEW', 'CHANGE_REQUESTED', 'RESUBMITTED', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_share_flag', sa.Boolean(), nullable=True),
    sa.Column('max_shares', sa.Numeric(precision=20), nullable=True),
    sa.Column('special_rights_flag', sa.Boolean(), nullable=True),
    sa.Column('share_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['share_class_id'], ['share_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_series_name'), 'share_series', ['name'], unique=False)
    op.create_table('amalgamating_businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('amalgamating', 'holding', 'primary', name='role'), nullable=False),
    sa.Column('foreign_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('foreign_jurisdiction_region', sa.String(length=10), nullable=True),
    sa.Column('foreign_name', sa.String(length=100), nullable=True),
    sa.Column('foreign_identifier', sa.String(length=50), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('amalgamation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amalgamation_id'], ['amalgamations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amalgamating_businesses_business_id'), 'amalgamating_businesses', ['business_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('middle_initial', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_first_name'), 'parties', ['first_name'], unique=False)
    op.create_index(op.f('ix_parties_middle_initial'), 'parties', ['middle_initial'], unique=False)
    op.create_table('review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_REVIEW', 'CHANGE_REQUESTED', 'RESUBMITTED', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cessation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sub_type', sa.String(length=20), nullable=True),
    sa.Column('signing_party_id', sa.Integer(), nullable=True),
    sa.Column('signing_date', sa.Date(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['signing_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolutions')
    op.drop_table('party_roles')
    op.drop_table('review_results')
    op.drop_index(op.f('ix_parties_middle_initial'), table_name='parties')
    op.drop_index(op.f('ix_parties_first_name'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_amalgamating_businesses_business_id'), table_name='amalgamating_businesses')
    op.drop_table('amalgamating_businesses')
    op.drop_index(op.f('ix_share_series_name'), table_name='share_series')
    op.drop_table('share_series')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_request_tracker_filing_id'), table_name='request_tracker')
    op.drop_index(op.f('ix_request_tracker_business_id'), table_name='request_tracker')
    op.drop_table('request_tracker')
    op.drop_index(op.f('ix_jurisdictions_filing_id'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_business_id'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    op.drop_index(op.f('ix_documents_filing_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_business_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('dc_issued_credentials')
    op.drop_table('consent_continuation_outs')
    op.drop_index(op.f('ix_comments_staff_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_filing_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_business_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('colin_event_ids')
    op.drop_index(op.f('ix_batch_processing_filing_id'), table_name='batch_processing')
    op.drop_index(op.f('ix_batch_processing_business_id'), table_name='batch_processing')
    op.drop_index(op.f('ix_batch_processing_batch_id'), table_name='batch_processing')
    op.drop_table('batch_processing')
    op.drop_index(op.f('ix_amalgamations_business_id'), table_name='amalgamations')
    op.drop_table('amalgamations')
    op.drop_index(op.f('ix_addresses_street'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_business_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address_type'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_share_classes_name'), table_name='share_classes')
    op.drop_table('share_classes')
    op.drop_index(op.f('ix_offices_business_id'), table_name='offices')
    op.drop_table('offices')
    op.drop_index(op.f('ix_furnishings_furnishing_group_id'), table_name='furnishings')
    op.drop_index(op.f('ix_furnishings_business_id'), table_name='furnishings')
    op.drop_index(op.f('ix_furnishings_batch_id'), table_name='furnishings')
    op.drop_table('furnishings')
    op.drop_table('filings')
    op.drop_table('dc_issued_business_user_credentials')
    op.drop_table('dc_connections')
    op.drop_index(op.f('ix_aliases_alias'), table_name='aliases')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_naics_elements_year'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_version'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_naics_structure_id'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_level'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_element_type'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_element_description'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_code'), table_name='naics_elements')
    op.drop_index(op.f('ix_naics_elements_class_title'), table_name='naics_elements')
    op.drop_table('naics_elements')
    op.drop_index(op.f('ix_furnishing_groups_xml_payload_id'), table_name='furnishing_groups')
    op.drop_table('furnishing_groups')
    op.drop_index(op.f('ix_businesses_tax_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_legal_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_identifier'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('xml_payloads')
    op.drop_index(op.f('ix_users_version_username'), table_name='users_version')
    op.drop_index(op.f('ix_users_version_transaction_id'), table_name='users_version')
    op.drop_index(op.f('ix_users_version_operation_type'), table_name='users_version')
    op.drop_index(op.f('ix_users_version_idp_userid'), table_name='users_version')
    op.drop_index(op.f('ix_users_version_end_transaction_id'), table_name='users_version')
    op.drop_table('users_version')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_idp_userid'), table_name='users')
    op.drop_table('users')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_share_series_version_transaction_id'), table_name='share_series_version')
    op.drop_index(op.f('ix_share_series_version_operation_type'), table_name='share_series_version')
    op.drop_index(op.f('ix_share_series_version_name'), table_name='share_series_version')
    op.drop_index(op.f('ix_share_series_version_end_transaction_id'), table_name='share_series_version')
    op.drop_table('share_series_version')
    op.drop_index(op.f('ix_share_classes_version_transaction_id'), table_name='share_classes_version')
    op.drop_index(op.f('ix_share_classes_version_operation_type'), table_name='share_classes_version')
    op.drop_index(op.f('ix_share_classes_version_name'), table_name='share_classes_version')
    op.drop_index(op.f('ix_share_classes_version_end_transaction_id'), table_name='share_classes_version')
    op.drop_table('share_classes_version')
    op.drop_index(op.f('ix_resolutions_version_transaction_id'), table_name='resolutions_version')
    op.drop_index(op.f('ix_resolutions_version_operation_type'), table_name='resolutions_version')
    op.drop_index(op.f('ix_resolutions_version_end_transaction_id'), table_name='resolutions_version')
    op.drop_table('resolutions_version')
    op.drop_index(op.f('ix_registration_bootstrap_account'), table_name='registration_bootstrap')
    op.drop_table('registration_bootstrap')
    op.drop_index(op.f('ix_party_roles_version_transaction_id'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_operation_type'), table_name='party_roles_version')
    op.drop_index(op.f('ix_party_roles_version_end_transaction_id'), table_name='party_roles_version')
    op.drop_table('party_roles_version')
    op.drop_index(op.f('ix_parties_version_transaction_id'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_operation_type'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_middle_initial'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_first_name'), table_name='parties_version')
    op.drop_index(op.f('ix_parties_version_end_transaction_id'), table_name='parties_version')
    op.drop_table('parties_version')
    op.drop_index(op.f('ix_offices_version_transaction_id'), table_name='offices_version')
    op.drop_index(op.f('ix_offices_version_operation_type'), table_name='offices_version')
    op.drop_index(op.f('ix_offices_version_end_transaction_id'), table_name='offices_version')
    op.drop_index(op.f('ix_offices_version_business_id'), table_name='offices_version')
    op.drop_table('offices_version')
    op.drop_table('office_types')
    op.drop_index(op.f('ix_naics_structures_year'), table_name='naics_structures')
    op.drop_index(op.f('ix_naics_structures_version'), table_name='naics_structures')
    op.drop_index(op.f('ix_naics_structures_level'), table_name='naics_structures')
    op.drop_index(op.f('ix_naics_structures_code'), table_name='naics_structures')
    op.drop_index(op.f('ix_naics_structures_class_title'), table_name='naics_structures')
    op.drop_index(op.f('ix_naics_structures_class_definition'), table_name='naics_structures')
    op.drop_table('naics_structures')
    op.drop_index(op.f('ix_jurisdictions_version_transaction_id'), table_name='jurisdictions_version')
    op.drop_index(op.f('ix_jurisdictions_version_operation_type'), table_name='jurisdictions_version')
    op.drop_index(op.f('ix_jurisdictions_version_filing_id'), table_name='jurisdictions_version')
    op.drop_index(op.f('ix_jurisdictions_version_end_transaction_id'), table_name='jurisdictions_version')
    op.drop_index(op.f('ix_jurisdictions_version_business_id'), table_name='jurisdictions_version')
    op.drop_table('jurisdictions_version')
    op.drop_index(op.f('ix_documents_version_transaction_id'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_operation_type'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_filing_id'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_end_transaction_id'), table_name='documents_version')
    op.drop_index(op.f('ix_documents_version_business_id'), table_name='documents_version')
    op.drop_table('documents_version')
    op.drop_table('dc_definitions')
    op.drop_table('corp_types')
    op.drop_table('configurations')
    op.drop_table('colin_last_update')
    op.drop_index(op.f('ix_businesses_version_transaction_id'), table_name='businesses_version')
    op.drop_index(op.f('ix_businesses_version_tax_id'), table_name='businesses_version')
    op.drop_index(op.f('ix_businesses_version_operation_type'), table_name='businesses_version')
    op.drop_index(op.f('ix_businesses_version_legal_name'), table_name='businesses_version')
    op.drop_index(op.f('ix_businesses_version_identifier'), table_name='businesses_version')
    op.drop_index(op.f('ix_businesses_version_end_transaction_id'), table_name='businesses_version')
    op.drop_table('businesses_version')
    op.drop_table('batches')
    op.drop_index(op.f('ix_amalgamations_version_transaction_id'), table_name='amalgamations_version')
    op.drop_index(op.f('ix_amalgamations_version_operation_type'), table_name='amalgamations_version')
    op.drop_index(op.f('ix_amalgamations_version_end_transaction_id'), table_name='amalgamations_version')
    op.drop_index(op.f('ix_amalgamations_version_business_id'), table_name='amalgamations_version')
    op.drop_table('amalgamations_version')
    op.drop_index(op.f('ix_amalgamating_businesses_version_transaction_id'), table_name='amalgamating_businesses_version')
    op.drop_index(op.f('ix_amalgamating_businesses_version_operation_type'), table_name='amalgamating_businesses_version')
    op.drop_index(op.f('ix_amalgamating_businesses_version_end_transaction_id'), table_name='amalgamating_businesses_version')
    op.drop_index(op.f('ix_amalgamating_businesses_version_business_id'), table_name='amalgamating_businesses_version')
    op.drop_table('amalgamating_businesses_version')
    op.drop_index(op.f('ix_aliases_version_transaction_id'), table_name='aliases_version')
    op.drop_index(op.f('ix_aliases_version_operation_type'), table_name='aliases_version')
    op.drop_index(op.f('ix_aliases_version_end_transaction_id'), table_name='aliases_version')
    op.drop_index(op.f('ix_aliases_version_alias'), table_name='aliases_version')
    op.drop_table('aliases_version')
    op.drop_index(op.f('ix_addresses_version_transaction_id'), table_name='addresses_version')
    op.drop_index(op.f('ix_addresses_version_street'), table_name='addresses_version')
    op.drop_index(op.f('ix_addresses_version_operation_type'), table_name='addresses_version')
    op.drop_index(op.f('ix_addresses_version_end_transaction_id'), table_name='addresses_version')
    op.drop_index(op.f('ix_addresses_version_business_id'), table_name='addresses_version')
    op.drop_index(op.f('ix_addresses_version_address_type'), table_name='addresses_version')
    op.drop_table('addresses_version')
    # ### end Alembic commands ###
