"""backfill_cutoff_filing_id

Revision ID: b42a474558f0
Revises: dbf687803623
Create Date: 2025-08-25 17:36:17.540478

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b42a474558f0'
down_revision = 'dbf687803623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('backfill_cutoff_filing_id', sa.Integer(), nullable=True))
    op.add_column('businesses_version', sa.Column('backfill_cutoff_filing_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'backfill_cutoff_filing_id')
    op.drop_column('businesses', 'backfill_cutoff_filing_id')

    # ### end Alembic commands ###
