"""court order

Revision ID: 1cdc6fdbf4cf
Revises: bc62c64eeaab
Create Date: 2026-07-09 15:57:16.422059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cdc6fdbf4cf'
down_revision = 'bc62c64eeaab'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filing_id', sa.Integer(), nullable=False),
        sa.Column('business_id', sa.Integer(), nullable=False),
        sa.Column('file_number', sa.String(length=20), nullable=True),
        sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('effect_of_order', sa.String(length=20), nullable=True),
        sa.Column('order_details', sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
        sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('court_orders_version',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filing_id', sa.Integer(), nullable=False),
        sa.Column('business_id', sa.Integer(), nullable=False),
        sa.Column('file_number', sa.String(length=20), nullable=True),
        sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('effect_of_order', sa.String(length=20), nullable=True),
        sa.Column('order_details', sa.String(length=2000), nullable=True),
        sa.Column('transaction_id', sa.BigInteger(), nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
        sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
        sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_court_orders_version_end_transaction_id'), 'court_orders_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_court_orders_version_operation_type'), 'court_orders_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_court_orders_version_transaction_id'), 'court_orders_version', ['transaction_id'], unique=False)

    # Migrate data from filings to court_orders
    op.execute(
        """
        INSERT INTO court_orders (filing_id, business_id, file_number, order_date, effect_of_order, order_details)
        SELECT id, business_id, court_order_file_number, court_order_date, court_order_effect_of_order, 
            case when filing_type = 'courtOrder' then order_details else null end as order_details
        FROM filings
        WHERE status='COMPLETED' and court_order_file_number is not null and trim(court_order_file_number) <> ''
        """
    )
    op.execute(
        """
        INSERT INTO court_orders_version (id, filing_id, business_id, file_number, order_date, effect_of_order, order_details, transaction_id, operation_type)
        SELECT c.id, c.filing_id, c.business_id, c.file_number, c.order_date, c.effect_of_order, c.order_details, f.transaction_id, 0
        FROM court_orders c
        join filings f on c.filing_id = f.id
        """
    )
    op.execute(
        """
        UPDATE filings
        SET order_details = null
        WHERE filing_type = 'courtOrder' and status='COMPLETED'
        """
    )

    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.alter_column('order_details', new_column_name='details')
        batch_op.drop_column('court_order_file_number')
        batch_op.drop_column('court_order_effect_of_order')
        batch_op.drop_column('court_order_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_order_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('court_order_effect_of_order', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('court_order_file_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('details', new_column_name='order_details')

    # Migrate data back from orders to filings
    op.execute(
        """
        UPDATE filings
        SET court_order_file_number = o.file_number,
            court_order_date = o.order_date,
            court_order_effect_of_order = o.effect_of_order,
            order_details = o.order_details
        FROM court_orders o
        WHERE filings.id = o.filing_id;
        """
    )

    op.drop_table('court_orders')
    op.drop_table('court_orders_version')
    
    # ### end Alembic commands ###
