"""empty message

Revision ID: 2fd104a5f3b5
Revises: e7abbdeb252a
Create Date: 2023-06-27 07:07:08.006306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fd104a5f3b5"
down_revision = "e7abbdeb252a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("party_roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("change_filing_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "filings", ["change_filing_id"], ["id"])

    with op.batch_alter_table("party_roles_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("change_filing_id", sa.Integer(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(None, "filings", ["change_filing_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("party_roles_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("change_filing_id")

    with op.batch_alter_table("party_roles", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("change_filing_id")

    # ### end Alembic commands ###
