"""empty message

Revision ID: e6ed22dc70ca
Revises: 1215735c3563
Create Date: 2019-07-03 14:25:05.759877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eed22dc70ca'
down_revision = '2bc4b2533f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE batch_custom_identifier START 100000")
    op.execute("CREATE SEQUENCE business_identifier_bc START 100000")
    op.execute("CREATE SEQUENCE business_identifier_c START 100000")
    op.execute("CREATE SEQUENCE business_identifier_coop START 1002395")
    op.execute("CREATE SEQUENCE business_identifier_sp_gp START 100000")
    op.execute("CREATE SEQUENCE grouping_identifier START 1")    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE batch_custom_identifier")
    op.execute("DROP SEQUENCE business_identifier_bc")
    op.execute("DROP SEQUENCE business_identifier_c")
    op.execute("DROP SEQUENCE business_identifier_coop")
    op.execute("DROP SEQUENCE business_identifier_sp_gp")
    op.execute("DROP SEQUENCE grouping_identifier")
    # ### end Alembic commands ###
