"""empty message

Revision ID: 4a27dc3cf7bc
Revises: edbd0f6ef10e
Create Date: 2026-02-20 14:09:53.369484

"""
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a27dc3cf7bc'
down_revision = 'edbd0f6ef10e'
branch_labels = None
depends_on = None

PERMISSION_NAME = 'TRANSITION_FILING'
ROLE_NAME = 'public_user'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    now = datetime.now(UTC)
    bind = op.get_bind()
    role = bind.execute(sa.text(f"SELECT id FROM authorized_roles where role_name= :rname").bindparams(rname=ROLE_NAME)).mappings().first()
    role_id = role['id']

    permission = bind.execute(sa.text(f"SELECT id FROM permissions WHERE permission_name = :pname").bindparams(pname=PERMISSION_NAME)).mappings().first()
    permission_id = permission['id']

    authorized_role_permissions = sa.table(
        'authorized_role_permissions',
        sa.column('role_id', sa.Integer),
        sa.column('permission_id', sa.Integer),
        sa.column('created_date', sa.TIMESTAMP(timezone=True)),
        sa.column('last_modified', sa.TIMESTAMP(timezone=True)),
        sa.column('created_by_id', sa.Integer),
        sa.column('modified_by_id', sa.Integer)
    )
    new_role_permission_list = [
        {
            'role_id': role_id,
            'permission_id': permission_id,
            'created_date': now,
            'last_modified': now,
            'created_by_id': None,
            'modified_by_id': None
        }
    ]
    op.bulk_insert(authorized_role_permissions, new_role_permission_list)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    bind = op.get_bind()
    role = bind.execute(sa.text(f"SELECT id FROM authorized_roles where role_name= :rname").bindparams(rname=ROLE_NAME)).mappings().first()
    role_id = role['id']

    permission = bind.execute(sa.text(f"SELECT id FROM permissions WHERE permission_name = :pname").bindparams(pname=PERMISSION_NAME)).mappings().first()
    permission_id = permission['id']

    op.execute(sa.text(
        "DELETE FROM authorized_role_permissions WHERE permission_id = :pid AND role_id = :rid"
        ).bindparams(pid=permission_id, rid=role_id))