"""empty message

Revision ID: b5ded56cab5b
Revises: 2467e09986f2
Create Date: 2026-03-13 09:27:35.973908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5ded56cab5b'
down_revision = '2467e09986f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('lear_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'lear_only')
    # ### end Alembic commands ###
