[project]
name = "document-record-service"
version = "0.1.0"
description = ""
authors = [
    {name = "Brandon.Galli@gov.bc.ca"},
]
readme = "README.md"
requires-python = ">=3.9,<4"
dependencies = [
    # "business-model @ git+https://github.com/bcgov/lear.git@main#subdirectory=python/common/business-registry-model",
    "flask (>=1.1.2,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "requests (>=2.32.4,<3.0.0)",
    "pypdf (>=5.7.0,<6.0.0)",
]

[tool.poetry]
packages = [{include = "document_record_service", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
black = "^25.1.0"
flake8 = "^7.3.0"
isort = "^6.0.1"

[tool.flake8]
ignore = ["F401","E402", "Q000", "E203", "W503"]
exclude = [
    ".venv",
    ".git",
    ".history",
    "devops",
    "tests",
    "*migrations*",
]
per-file-ignores = [
    "__init__.py:F401",
    "*.py:B902"
]
max-line-length = 120
docstring-min-length=10
count = true

[tool.black]
target-version =  ["py310", "py311", "py312"]
line-length = 120

[tool.isort]
atomic = true
profile = "black"
line_length = 120

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
