# Pay API Specification 
swagger: "2.0"
info:
  title: Pay API
  description: Payment API for Fees and Payment components
  version: "1.0.0"
# the domain of the service
host: pay-api-dev.pathfinder.gov.bc.ca
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /pay-api/v1
securityDefinitions:
  Bearer:
      type: apiKey
      name: Authorization
      in: header
produces:
  - application/json
paths:
  /fees:
    post:
      summary: Calculate fees for filing
      description: Returns the fee information based on the input parameters.
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Fee charge information for calculating the fees"
          required: true
          schema:
            $ref: "#/definitions/FeeChargeCodes"
      responses:
        405:
          description: "Invalid input"
        201:
          description: Fees
          content:
            application/json:
              schema:
                $ref: '#/definitions/Fee'
      security: 

  /payments:
    post:
      summary: Make payment records for the filing
      description: Make payment records for the filing
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Payment Request"
        required: true
        schema:
          $ref: "#/definitions/FeeChargeCodes"
      responses:
        405:
          description: "Invalid input"
        201:
          description: PaymentTransaction
          content:
            application/json:
              schema:
                $ref: '#/definitions/PaymentTransaction'
      security: 
  /payments/{filingId}:
    post:
      summary: Make payment records for the filing
      description: Make payment records for the filing
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: filingId
        description: "Filing Identifier"
        required: true
        schema:
          type: string
      responses:
        201:
          description: PaymentTransaction
          content:
            application/json:
              schema:
                $ref: '#/definitions/PaymentTransaction'
      security: 

definitions:
  PaymentTransaction:
    properties:
      filingId:
        type: string
        description: Identifier for the filing.
      transactionId:
        type: string
        description: Transaction identifier for the payment.
  FeeChargeCodes:
    properties:
      entityType:
        type: string
        description: Identifier for the entity. E.g, COOPS
      filingId:
        type: string
        description: Identifier for the filing.
      methodOfPayment:
        type: string
        description: Method of Payment. E.g, CC
      feeCharges:
        type: array
        items: 
          $ref: "#/definitions/FeeChargeCode"
  FeeChargeCode:
    properties:
      feeChargeCode:
        type: string
        description: Fee Charge Code against which fee will be applied
      priorityIndicator:
        type: string
        description: Y or N value for priority processing
      description:
        type: string
        description: Display name of line item.
  Fee:
    properties:
      totalFees:
        type: integer
        description: Total Fees for the filing
      totalTaxes:
        type: integer
        description: Total Taxes for the filing
      nettAmount:
        type: integer
        description: Nett amount for the filing
      currency:
        type: string
        description: currency
      feeItems:
        type: array
        items: 
          $ref: "#/definitions/FeeItem"
  FeeItem:
    properties:
      fee:
        type: integer
        description: Fee for the fee item
      description:
        type: string
        description: Description of the fee item
      tax:
        type: integer
        description: Tax for the fee item
