name: Business Furnishings Job CI

on:
  pull_request:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "gcp-jobs/furnishings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/furnishings

jobs:
  business-furnishings-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-furnishings"
      working_directory: "./gcp-jobs/furnishings"
      codecov_flag: "business-furnishings"