name: Business Digital Credentials Queue Service CI

on:
  pull_request:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "queue_services/business-digital-credentials/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/business-digital-credentials

jobs:
  business-digital-credentials-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-digital-credentials"
      working_directory: "./queue_services/business-digital-credentials"
      codecov_flag: "business-digital-credentials"
