name: Business Update Legal Filings Job CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "jobs/update-legal-filings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/update-legal-filings

jobs:
  business-update-legal-filings-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-future-effective-filings"
      working_directory: "./jobs/update-legal-filings"
      codecov_flag: "legalfilings"