name: Business Update Colin Filings Job CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "jobs/update-colin-filings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/update-colin-filings

jobs:
  business-update-colin-filings-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-update-colin-filings"
      working_directory: "./jobs/update-colin-filings"
      codecov_flag: "updatecolin"
