name: Business Filer CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "queue_services/entity-filer/**"
      - "queue_services/common/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/entity-filer

jobs:
  business-filer-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-filer"
      working_directory: "./queue_services/entity-filer"
      codecov_flag: "entityfiler"
