name: Email Reminder Job CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "jobs/email-reminder/**"

defaults:
  run:
    shell: bash
    working-directory: ./jobs/email-reminder

jobs:
  setup-job:
    runs-on: ubuntu-24.04

    if: github.repository == 'bcgov/lear'

    steps:
      - uses: actions/checkout@v3
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Lint with pylint
        id: pylint
        run: |
          make pylint
      - name: Lint with flake8
        id: flake8
        run: |
          make flake8

  # testing:
  #   needs: setup-job
  #   runs-on: ubuntu-24.04
  #   strategy:
  #     matrix:
  #       python-version: [3.8]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install dependencies
  #       run: |
  #         make setup
  #     - name: Test with pytest
  #       id: test
  #       run: |
  #         make test

  build-check:
    needs: setup-job
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: build to check strictness
        id: build
        run: |
          make build-nc
