name: Entity Emailer CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "queue_services/entity-emailer/**"
      - "queue_services/common/**"

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/entity-emailer

jobs:
  setup-job:
    runs-on: ubuntu-24.04

    if: github.repository == 'bcgov/lear'

    steps:
      - uses: actions/checkout@v3
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Lint with pylint
        id: pylint
        run: |
          make pylint
      - name: Lint with flake8
        id: flake8
        run: |
          make flake8

  testing:
    needs: setup-job
    env:
      DATABASE_TEST_USERNAME: postgres
      DATABASE_TEST_PASSWORD: postgres
      DATABASE_TEST_NAME: postgres
      DATABASE_TEST_HOST: localhost
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: postgres
      TRACKER_DATABASE_TEST_USERNAME: postgres
      TRACKER_DATABASE_TEST_PASSWORD: postgres
      TRACKER_DATABASE_TEST_NAME: postgres
      TRACKER_DATABASE_TEST_HOST: localhost
      TRACKER_DATABASE_TEST_PORT: 5433
      NATS_SERVERS: "nats://nats:4222"
      NATS_CLIENT_NAME: entity.email.tester
      NATS_CLUSTER_ID: test-cluster
      NATS_FILER_SUBJECT: entity.email
      NATS_QUEUE: entity-email-worker
      JWT_OIDC_JWKS_CACHE_TIMEOUT: 300
      TEMPLATE_PATH: /home/runner/work/lear/lear/queue_services/entity-emailer/src/entity_emailer/email_templates
      DASHBOARD_URL: https://dev.bcregistry.ca/businesses/
      TEST_NATS_DOCKER: True
      STAN_CLUSTER_NAME: test-cluster

    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      postgres-tracker:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Test with pytest
        id: test
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./queue_services/entity-emailer/coverage.xml
          flags: entityemailer
          name: codecov-entity-emailer
          token: ${{ secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false

  build-check:
    needs: setup-job
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: build to check strictness
        id: build
        run: |
          make build-nc
