name: Entity Filer CD

on:
  push:
    branches:
      - master
    paths:
      - "queue_services/entity-filer/**"
      - "queue_services/common/**"
  workflow_dispatch:
    inputs:
      environement:
        description: "Environment (dev/test)"
        required: true
        default: "dev"

jobs:
  entity-filer-cd:
    runs-on: ubuntu-latest
    if: github.repository == 'bcgov/lear'
    steps:
      - uses: actions/checkout@v2
      - name: Set env by input
        run: |
          echo "::set-env name=TAG_NAME::${{ github.event.inputs.environement }}"

      - name: Set env by master branch
        if: env.TAG_NAME == '' && github.ref == 'refs/heads/master'
        run: |
          echo "::set-env name=TAG_NAME::dev"

      - uses: pwei1018/bcrs-cd-action@latest
        with:
          WORKING_DIRECTORY: "./queue_services/entity-filer"
          APP_NAME: "entity-filer"
          VAULTS: '[{ \"vault\": \"shared\", \"application\": [\"nats\"]}, {\"vault\": \"entity\",\"application\": [\"postgres-legal\", \"entity-filer\", \"nats-filer\", \"entity-service-account\", \"sentry\"]}]'
          SKIP_OP: "false"
          OP_PARAMETERS: ${{ secrets.OP_PARAMETERS }}
          OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_LOGIN_REGISTRY }}
          OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT_DOCKER_REGISTRY }}
          OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_SA_NAME }}
          OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
          OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}
          OPENSHIFT_REPOSITORY_DEPLOYMENT: ${{ secrets.OPENSHIFT_REPOSITORY }}

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*Entity Filer Built and Deployed to ${{env.TAG_NAME}}*"
          channel: "#registries-bot"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
