name: entity-emailer PR CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "queue_services/entity-emailer/**"
      - "queue_services/common/**"


jobs:
  pr-checks:
    env:
      DATABASE_TEST_USERNAME: postgres
      DATABASE_TEST_PASSWORD: postgres
      DATABASE_TEST_NAME: postgres
      DATABASE_TEST_HOST: localhost
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: postgres
      NATS_SERVERS: "nats://nats:4222"
      NATS_CLIENT_NAME: entity.email.tester
      NATS_CLUSTER_ID: test-cluster
      NATS_FILER_SUBJECT: entity.email
      NATS_QUEUE: entity-email-worker
      JWT_OIDC_JWKS_CACHE_TIMEOUT: 300

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7,3.8]

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./queue_services/entity-emailer
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/dev.txt
      - name: Lint with pylint
        working-directory: ./queue_services/entity-emailer
        run: |
          pylint --rcfile=setup.cfg --load-plugins=pylint_flask src
      - name: Lint with flake8
        working-directory: ./queue_services/entity-emailer
        run: |
          flake8 src tests
#      - name: Test with pytest
#        working-directory: ./queue_services/entity-emailer
#        run: |
#          pip install .
#          pytest
