name: FURNISHINGS GCP CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/furnishings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/furnishings

jobs:
  furnishings-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "furnishings"
      working_directory: "./gcp-jobs/furnishings"
      codecov_flag: "furnishings"