name: GCP Filings Notebook Report CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/filings-notebook-report/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/filings-notebook-report

jobs:
  filings-notebook-report-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "filings-notebook-report"
      working_directory: "./gcp-jobs/filings-notebook-report"
      codecov_flag: "filings-notebook-report"