name: Update Colin Filings Job GCP CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/update-colin-filings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/update-colin-filings

jobs:
  update-colin-filings-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "update-colin-filings"
      working_directory: "./gcp-jobs/update-colin-filings"
      codecov_flag: "updatecolinfilings"