name: GCP Email Reminder Job CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/email-reminder/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/email-reminder

jobs:
  email-reminder-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "email-reminder"
      working_directory: "./gcp-jobs/email-reminder"
      codecov_flag: "email-reminder"