name: GCP Involuntary Dissolutions CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/involuntary-dissolutions/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/involuntary-dissolutions

jobs:
  involuntary-dissolutions-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "involuntary-dissolutions"
      working_directory: "./gcp-jobs/involuntary-dissolutions"
      codecov_flag: "involuntary-dissolutions"