name: GCP Entity BN CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/entity-bn/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/entity-bn

jobs:
  entity-bn-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "entity-bn"
      working_directory: "./gcp-jobs/entity-bn"
      codecov_flag: "entity-bn"