name: GCP Jobs CD

on:
  push:
    branches:
      - main
    paths:
      - "gcp-jobs/**"
  workflow_dispatch:
    inputs:
      target:
        required: true
        type: string
        default: "dev"
      app_name:
        required: true
        type: string
        default: "lear"
      working_directory:
        type: string
        default: "./gcp-jobs"
      redeploy:
        type: string
        default: "false"

jobs:
  setup:
    # Only allow run the CD flow in protected branch
    if: github.ref_protected == true

    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash

    # Allow add the tag in the repo.
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'none'

    outputs:
      TARGETS: ${{ steps.setenv.outputs.TARGETS }}
      TARGET: ${{ steps.setenv.outputs.TARGET }}
      TARGET_FROM: ${{ steps.setenv.outputs.TARGET_FROM }}
      PIPELINE: ${{ steps.setenv.outputs.PIPELINE }}

    steps:
      # Checkout code
      - name: Checkout out the code
        uses: actions/checkout@v4

      - name: Setup targets
        uses: bcgov/bcregistry-sre/.github/actions/setup-deployment-target@main
        with:
          environment: ${{ inputs.target }}
          app_name: ${{ inputs.app_name }}

      - id: setenv
        run: |
          echo "TARGETS=${{ env.DEPLOY_TARGETS }}" >> "$GITHUB_OUTPUT"
          echo "TARGET=${{ env.DEPLOY_TARGET }}" >> "$GITHUB_OUTPUT"
          echo "TARGET_FROM=${{ env.DEPLOY_TARGET_FROM }}" >> "$GITHUB_OUTPUT"
          echo "PIPELINE=${{ env.DEPLOY_PIPELINE }}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: setup
    runs-on: ubuntu-24.04

    environment:
      name: "${{ needs.setup.outputs.TARGET }}"

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    # Allow add the tag in the repo.
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      # Checkout code
      - name: Checkout out the code
        uses: actions/checkout@v4

      # Copy cloud build, cloud deploy and skaffold yaml files to the build
      - name: Copy deployment files
        uses: bcgov/bcregistry-sre/.github/actions/backend-deploy-job@main
        with:
          working-directory: ${{ inputs.working_directory }}

      # GCP authentication
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Trigger Cloud Deploy
      - name: Deployment
        working-directory: ${{ inputs.working_directory }}
        run: |-
          SHORT_SHA=$(git rev-parse --short HEAD)

          echo "SHORT_SHA: $SHORT_SHA"

          TARGET_FROM="${{ needs.setup.outputs.TARGET_FROM }}"

          if [ -z ${{ needs.setup.outputs.TARGET_FROM }}]; then
            TARGET_FROM="${{ needs.setup.outputs.TARGET }}"
          fi

          for dir in ./*/     # list directories in the form "/./dirname/"
          do
              dir=${dir%*/}      # remove the trailing "/"
              JOB_NAME="${dir##*/}"    # print everything after the final "/"
              echo "TARGET_FROM: $TARGET_FROM"
              gcloud builds submit \
                --region=northamerica-northeast1 \
                --substitutions _SHORT_SHA=$SHORT_SHA,_APP_NAME="${{ inputs.app_name }}-$JOB_NAME",_DEPLOYMENT_ENVS="${{ needs.setup.outputs.TARGETS }}",_DEPLOYMENT_ENV="${{ needs.setup.outputs.TARGET }}",_DEPLOYMENT_ENV_FROM="$TARGET_FROM",_DEPLOYMENT_PIPELINE="${{ needs.setup.outputs.PIPELINE }}",_REDEPLOY="${{ inputs.redeploy}}" \
                --config devops/gcp/cloudbuild.yaml
          done