name: GCP Expired Limited Restoration CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/expired-limited-restoration/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/expired-limited-restoration

jobs:
  expired-limited-restoration-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "expired-limited-restoration"
      working_directory: "./gcp-jobs/expired-limited-restoration"
      codecov_flag: "expired-limited-restoration"
