name: Business API OAS CI

on:
  pull_request:
    paths:
      - "docs/**"

defaults:
  run:
    shell: bash
    working-directory: .

permissions:
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install spectral
        run: npm install --location=global @stoplight/spectral-cli
      - name: Run spectral
        run: spectral lint docs/business.yaml --ruleset .spectral.yml --verbose
