name: Schemas PR CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "schemas/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./schemas
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/dev.txt
      - name: Lint with pylint
        run: |
          working-directory: ./schemas
          pylint --rcfile=setup.cfg --load-plugins=pylint_flask src
      - name: Lint with flake8
        run: |
          working-directory: ./schemas
          flake8 src tests
      - name: Test with pytest
        run: |
          working-directory: ./schemas
          pytest
