apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    name: ${NAME}
  name: ${NAME}-cronjob
objects:
- kind: "CronJob"
  apiVersion: "batch/v1"
  metadata:
    name: "${NAME}-${TAG}"
    labels:
      name: "${NAME}"
      environment: "${TAG}"
      role: "${ROLE}"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: ${SUCCESS_JOBS_HISTORY_LIMIT}
    failedJobsHistoryLimit: ${FAILED_JOBS_HISTORY_LIMIT}
    jobTemplate:
      metadata:
        labels:
          name: "${NAME}"
          environment: "${TAG}"
          role: "${ROLE}"
      spec:
        backoffLimit: ${JOB_BACKOFF_LIMIT}
        template:
          metadata:
            labels:
              name: "${NAME}"
              environment: "${TAG}"
              role: "${ROLE}"
          spec:
            containers:
              - name: "${NAME}-${TAG}"
                image: "${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${NAME}:${TAG}"
                resources:
                  limits:
                    cpu: '1'
                    memory: 3Gi
                  requests:
                    cpu: 250m
                    memory: 1Gi
                imagePullPolicy: Always
                env:
                  - name: DATABASE_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: business-notebook-secret-prod
                        key: DATABASE_USERNAME
                  - name: DATABASE_NAME
                    valueFrom:
                      secretKeyRef:
                        name: business-notebook-secret-prod
                        key: DATABASE_NAME
                  - name: LEAR_DB_CONNECTION_NAME
                    valueFrom:
                      secretKeyRef:
                        name: business-notebook-secret-prod
                        key: LEAR_DB_CONNECTION_NAME
                  - name: GOOGLE_APPLICATION_CREDENTIALS
                    value: /var/secrets/google/a083gt-prod-2edf46bc7938.json
                  - name: APP_FILE
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: APP_FILE
                  - name: SENDER_EMAIL
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SENDER_EMAIL
                  - name: ERROR_EMAIL_RECIPIENTS
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: ERROR_EMAIL_RECIPIENTS
                  - name: EMAIL_SMTP
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: EMAIL_SMTP
                  - name: ENVIRONMENT
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: ENVIRONMENT
                  - name: BCREG_FTP_PRIVATE_KEY
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: BCREG_FTP_PRIVATE_KEY
                  - name: BCREG_FTP_PRIVATE_KEY_PASSPHRASE
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: BCREG_FTP_PRIVATE_KEY_PASSPHRASE
                  - name: SFTP_HOST
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SFTP_HOST
                  - name: SFTP_PORT
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SFTP_PORT
                  - name: SFTP_HOST_KEY
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SFTP_HOST_KEY
                  - name: SFTP_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SFTP_USERNAME
                  - name: SFTP_VERIFY_HOST
                    valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${TAG}-secret
                        key: SFTP_VERIFY_HOST
                volumeMounts:
                  - name: gcp-sa-volume
                    readOnly: true
                    mountPath: /var/secrets/google
                  - name: data-volume
                    mountPath: /opt/app-root/data
            restartPolicy: Never
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 1600
            dnsPolicy: ClusterFirst
            volumes:
              - name: gcp-sa-volume
                secret:
                  secretName: gcp-sa
                  defaultMode: 420
              - name: data-volume
                emptyDir: {}
parameters: 

  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: sftp-icbc-report

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: job


  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: cc892f-tools

  - name: IMAGE_REGISTRY
    displayName: Image Registry
    required: true
    description: The image registry of the OpenShift project.
    value: image-registry.openshift-image-registry.svc:5000

  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job (using local cluster system TZ) to run at 0:55 * * TUE-SAT at pacific time so it will be 7:55 at UTC"
    value: "55 7 * * TUE-SAT"
    required: true

  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true

  - name: "FAILED_JOBS_HISTORY_LIMIT"
    displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained"
    value: "2"
    required: true

  - name: "JOB_BACKOFF_LIMIT"
    displayName: "Job Backoff Limit"
    description: "The number of attempts to try for a successful job outcome"
    value: "0"
    required: false
